# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Operations

      class GetAtsApplicationsApplicationIdAttachmentsRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # The Kombo ID of the application you want to obtain attachments for.
        field :application_id, ::String, { 'path_param': { 'field_name': 'application_id', 'style': 'simple', 'explode': false } }
        # ID of the integration you want to interact with.
        field :integration_id, Crystalline::Nilable.new(::String), { 'header': { 'field_name': 'X-Integration-Id', 'style': 'simple', 'explode': false } }

        sig { params(application_id: ::String, integration_id: T.nilable(::String)).void }
        def initialize(application_id:, integration_id: nil)
          @application_id = application_id
          @integration_id = integration_id
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @application_id == other.application_id
          return false unless @integration_id == other.integration_id
          true
        end
      end
    end
  end
end
