# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Operations

      class PatchIntegrationsIntegrationIdIntegrationFieldsIntegrationFieldIdRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # PATCH /integrations/:integration_id/integration-fields/:integration_field_id Parameter
        field :integration_id, ::String, { 'path_param': { 'field_name': 'integration_id', 'style': 'simple', 'explode': false } }
        # PATCH /integrations/:integration_id/integration-fields/:integration_field_id Parameter
        field :integration_field_id, ::String, { 'path_param': { 'field_name': 'integration_field_id', 'style': 'simple', 'explode': false } }
        # PATCH /integrations/:integration_id/integration-fields/:integration_field_id Request body
        field :body, Models::Shared::PatchIntegrationsIntegrationIdIntegrationFieldsIntegrationFieldIdRequestBody, { 'request': { 'media_type': 'application/json' } }

        sig { params(integration_id: ::String, integration_field_id: ::String, body: Models::Shared::PatchIntegrationsIntegrationIdIntegrationFieldsIntegrationFieldIdRequestBody).void }
        def initialize(integration_id:, integration_field_id:, body:)
          @integration_id = integration_id
          @integration_field_id = integration_field_id
          @body = body
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @integration_id == other.integration_id
          return false unless @integration_field_id == other.integration_field_id
          return false unless @body == other.body
          true
        end
      end
    end
  end
end
