# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module Kombo
  module Models
    module Errors
      autoload :APIError, 'open_api_sdk/models/errors/apierror.rb'
      autoload :KomboAtsError, 'open_api_sdk/models/errors/komboatserror.rb'
      autoload :KomboGeneralError, 'open_api_sdk/models/errors/kombogeneralerror.rb'
      autoload :KomboHrisError, 'open_api_sdk/models/errors/kombohriserror.rb'
    end
  end
end
