# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared
      # Fields specific to A3 Innuva Nómina.
      class A3innuvanomina
        extend T::Sig
        include Crystalline::MetadataFields

        # Required for illness absences. Benefit type: Delegated Payment, No Right to Benefit, or Direct payment.
        field :benefit_type_id, Crystalline::Nilable.new(Models::Shared::BenefitTypeId), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('benefit_type_id'), 'decoder': Utils.enum_from_string(Models::Shared::BenefitTypeId, true) } }

        sig { params(benefit_type_id: T.nilable(Models::Shared::BenefitTypeId)).void }
        def initialize(benefit_type_id: nil)
          @benefit_type_id = benefit_type_id
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @benefit_type_id == other.benefit_type_id
          true
        end
      end
    end
  end
end
