# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared

      class AssessmentOrderReceivedWebhookPayloadData
        extend T::Sig
        include Crystalline::MetadataFields

        # The unique identifier of the assessment order.
        field :id, ::String, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('id'), required: true } }
        # The identifier of the assessment package.
        field :package_id, ::String, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('package_id'), required: true } }
        # The current status of the assessment order.
        field :status, Models::Shared::AssessmentOrderReceivedWebhookPayloadStatus, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('status'), required: true, 'decoder': ::Kombo::Utils.enum_from_string(Models::Shared::AssessmentOrderReceivedWebhookPayloadStatus, false) } }
        # The unique identifier of the integration.
        field :integration_id, ::String, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('integration_id'), required: true } }
        # Information about the candidate taking the assessment.
        field :candidate, Models::Shared::AssessmentOrderReceivedWebhookPayloadCandidate, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('candidate'), required: true } }
        # Information about the job application.
        field :application, Models::Shared::AssessmentOrderReceivedWebhookPayloadApplication, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('application'), required: true } }
        # Information about the job posting.
        field :job, Models::Shared::AssessmentOrderReceivedWebhookPayloadJob, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('job'), required: true } }

        sig { params(id: ::String, package_id: ::String, status: Models::Shared::AssessmentOrderReceivedWebhookPayloadStatus, integration_id: ::String, candidate: Models::Shared::AssessmentOrderReceivedWebhookPayloadCandidate, application: Models::Shared::AssessmentOrderReceivedWebhookPayloadApplication, job: Models::Shared::AssessmentOrderReceivedWebhookPayloadJob).void }
        def initialize(id:, package_id:, status:, integration_id:, candidate:, application:, job:)
          @id = id
          @package_id = package_id
          @status = status
          @integration_id = integration_id
          @candidate = candidate
          @application = application
          @job = job
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @id == other.id
          return false unless @package_id == other.package_id
          return false unless @status == other.status
          return false unless @integration_id == other.integration_id
          return false unless @candidate == other.candidate
          return false unless @application == other.application
          return false unless @job == other.job
          true
        end
      end
    end
  end
end
