# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared

      class AttributeText
        extend T::Sig
        include Crystalline::MetadataFields


        field :label, ::String, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('label'), required: true } }

        field :value, ::String, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('value'), required: true } }

        field :type, ::String, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('type'), required: true } }

        sig { params(label: ::String, value: ::String, type: ::String).void }
        def initialize(label:, value:, type: 'TEXT')
          @label = label
          @value = value
          unless type == 'TEXT'
            raise ArgumentError, 'Invalid value for type'
          end
          @type = 'TEXT'
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @label == other.label
          return false unless @value == other.value
          return false unless @type == other.type
          true
        end
      end
    end
  end
end
