# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared

      class AttributeStatus < T::Enum
        enums do
          COMPLETED = new('COMPLETED')
          CANCELLED = new('CANCELLED')
        end
      end
    end
  end
end
