# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared
      # BenefitTypeId - Required for illness absences. Benefit type: Delegated Payment, No Right to Benefit, or Direct payment.
      class BenefitTypeId < T::Enum
        enums do
          DELEGATED_PAYMENT = new('Delegated Payment')
          NO_RIGHT_TO_BENEFIT = new('No Right to Benefit')
          DIRECT_PAYMENT = new('Direct payment')
        end
      end
    end
  end
end
