# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared
      # The data used to create or modify a Candidate Assessment.
      class CandidateAssessmentData
        extend T::Sig
        include Crystalline::MetadataFields

        # Information on a set of Assessment Test Results used in concert with the Candidate Assessment.
        field :assess_candidate_test_result_data, Crystalline::Nilable.new(Models::Shared::AssessCandidateTestResultData), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('Assess_Candidate_Test_Result_Data') } }

        sig { params(assess_candidate_test_result_data: T.nilable(Models::Shared::AssessCandidateTestResultData)).void }
        def initialize(assess_candidate_test_result_data: nil)
          @assess_candidate_test_result_data = assess_candidate_test_result_data
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @assess_candidate_test_result_data == other.assess_candidate_test_result_data
          true
        end
      end
    end
  end
end
