# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared
      # ConnectionFlowFailedWebhookPayloadType - Type of the webhook event
      class ConnectionFlowFailedWebhookPayloadType < T::Enum


        enums do
          CONNECTION_FLOW_FAILED = new('connection-flow-failed')
        end
      end
    end
  end
end
