# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared

      class ConnectionFlowFailedWebhookPayloadData
        extend T::Sig
        include Crystalline::MetadataFields

        # The name of the integrated tool (e.g., "personio", "greenhouse").
        field :integration_tool, ::String, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('integration_tool'), required: true } }
        # The category of the integration (HRIS, ATS, ASSESSMENT, or LMS).
        field :integration_category, Models::Shared::ConnectionFlowFailedWebhookPayloadIntegrationCategory, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('integration_category'), required: true, 'decoder': ::Kombo::Utils.enum_from_string(Models::Shared::ConnectionFlowFailedWebhookPayloadIntegrationCategory, false) } }
        # Information about the end user who created the integration.
        field :end_user, Models::Shared::ConnectionFlowFailedWebhookPayloadEndUser, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('end_user'), required: true } }
        # URL to view detailed logs for the operation.
        field :log_url, ::String, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('log_url'), required: true } }

        sig { params(integration_tool: ::String, integration_category: Models::Shared::ConnectionFlowFailedWebhookPayloadIntegrationCategory, end_user: Models::Shared::ConnectionFlowFailedWebhookPayloadEndUser, log_url: ::String).void }
        def initialize(integration_tool:, integration_category:, end_user:, log_url:)
          @integration_tool = integration_tool
          @integration_category = integration_category
          @end_user = end_user
          @log_url = log_url
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @integration_tool == other.integration_tool
          return false unless @integration_category == other.integration_category
          return false unless @end_user == other.end_user
          return false unless @log_url == other.log_url
          true
        end
      end
    end
  end
end
