# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared
      # ContentType - Content type of the note. Currently only `PLAIN_TEXT` is supported.
      class ContentType < T::Enum
        enums do
          PLAIN_TEXT = new('PLAIN_TEXT')
        end
      end
    end
  end
end
