# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared

      class ContentRef
        extend T::Sig
        include Crystalline::MetadataFields

        # The bucket the object was written to.
        field :bucket, ::String, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('bucket'), required: true } }
        # The full object key, including the prefix configured on the file destination.
        field :key, ::String, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('key'), required: true } }

        field :type, ::String, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('type'), required: true } }

        sig { params(bucket: ::String, key: ::String, type: ::String).void }
        def initialize(bucket:, key:, type: 's3')
          @bucket = bucket
          @key = key
          unless type == 's3'
            raise ArgumentError, 'Invalid value for type'
          end
          @type = 's3'
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @bucket == other.bucket
          return false unless @key == other.key
          return false unless @type == other.type
          true
        end
      end
    end
  end
end
