# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared

      class FormatSingleSelect
        extend T::Sig
        include Crystalline::MetadataFields


        field :options, Crystalline::Array.new(Models::Shared::Option1), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('options'), required: true } }

        field :type, ::String, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('type'), required: true } }

        field :display_type, Crystalline::Nilable.new(Models::Shared::DisplayType3), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('display_type'), 'decoder': ::Kombo::Utils.enum_from_string(Models::Shared::DisplayType3, true) } }

        sig { params(options: T::Array[Models::Shared::Option1], type: ::String, display_type: T.nilable(Models::Shared::DisplayType3)).void }
        def initialize(options:, type: 'SINGLE_SELECT', display_type: nil)
          @options = options
          unless type == 'SINGLE_SELECT'
            raise ArgumentError, 'Invalid value for type'
          end
          @type = 'SINGLE_SELECT'
          @display_type = display_type
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @options == other.options
          return false unless @type == other.type
          return false unless @display_type == other.display_type
          true
        end
      end
    end
  end
end
