# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared

      class GetAtsJobsPositiveResponseEmploymentType
        include ::Crystalline::Enum
        enums do
          FULL_TIME = new('FULL_TIME')
          PART_TIME = new('PART_TIME')
          CONTRACT = new('CONTRACT')
          SEASONAL = new('SEASONAL')
          INTERNSHIP = new('INTERNSHIP')
        end
        open!
      end
    end
  end
end
