# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared
      # GetAtsRolesPositiveResponseUnifiedType - Unified role type if Kombo can map it.
      class GetAtsRolesPositiveResponseUnifiedType < T::Enum


        enums do
          HIRING_MANAGER = new('HIRING_MANAGER')
          RECRUITER = new('RECRUITER')
          COORDINATOR = new('COORDINATOR')
          SOURCER = new('SOURCER')
          INTERVIEWER = new('INTERVIEWER')
          ADMIN = new('ADMIN')
        end
      end
    end
  end
end
