# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared
      # GetAtsAttachmentsPositiveResponseType - What the file is used for in the ATS. Anything that is neither a CV nor a cover letter is reported as `OTHER`.
      class GetAtsAttachmentsPositiveResponseType < T::Enum
        enums do
          CV = new('CV')
          COVER_LETTER = new('COVER_LETTER')
          OTHER = new('OTHER')
        end
      end
    end
  end
end
