# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared
      # GetAtsInterviewsPositiveResponseOutcome - Parsed status of the application. If Kombo identifies that the application was accepted and the candidate hired, it will be `HIRED`. If the application was rejected or the candidate declined, it will be `DECLINED`. If the application is still in process, it will be `PENDING`.
      # Kombo will always try to deliver this information as reliably as possible.
      class GetAtsInterviewsPositiveResponseOutcome < T::Enum


        enums do
          PENDING = new('PENDING')
          HIRED = new('HIRED')
          DECLINED = new('DECLINED')
        end
      end
    end
  end
end
