# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared

      class GetAtsJobsPositiveResponseStatus
        include ::Crystalline::Enum
        enums do
          OPEN = new('OPEN')
          CLOSED = new('CLOSED')
          DRAFT = new('DRAFT')
          ARCHIVED = new('ARCHIVED')
        end
        open!
      end
    end
  end
end
