# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared
      # GetHrisStaffingEntitiesPositiveResponseStatus - The status of the staffing entity.
      #         OPEN_LIMITED: The staffing entity is open and has a limited number of openings. Refer to the `number_of_openings` field to get the number of openings.
      #         OPEN_UNLIMITED: The staffing entity is open and has an unlimited number of openings. Some enterprise systems refer to this as "Evergreen".
      #         PENDING: The staffing entity is pending approval or is waiting to be published.
      #         FROZEN: The staffing entity is frozen (hiring freeze) and does not accept applications/hires.
      #         FILLED: The staffing entity is filled (to its maximum capacity) and not available for new hires.
      #         CLOSED: The staffing entity is closed and not available for new hires.
      class GetHrisStaffingEntitiesPositiveResponseStatus < T::Enum


        enums do
          OPEN_LIMITED = new('OPEN_LIMITED')
          OPEN_UNLIMITED = new('OPEN_UNLIMITED')
          PENDING = new('PENDING')
          FROZEN = new('FROZEN')
          FILLED = new('FILLED')
          CLOSED = new('CLOSED')
        end
      end
    end
  end
end
