# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared
      # GetHrisGroupsPositiveResponseType - Type of the group.
      class GetHrisGroupsPositiveResponseType < T::Enum


        enums do
          DEPARTMENT = new('DEPARTMENT')
          TEAM = new('TEAM')
          COST_CENTER = new('COST_CENTER')
        end
      end
    end
  end
end
