# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared

      class GetHrisEmployeesPositiveResponseGender
        include ::Crystalline::Enum
        enums do
          MALE = new('MALE')
          FEMALE = new('FEMALE')
          NON_BINARY = new('NON_BINARY')
          NOT_SPECIFIED = new('NOT_SPECIFIED')
        end
        open!
      end
    end
  end
end
