# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared
      # GetHrisEmployeesPositiveResponseUsedUnit - The time-unit of the used time.
      class GetHrisEmployeesPositiveResponseUsedUnit < T::Enum
        enums do
          HOURS = new('HOURS')
          DAYS = new('DAYS')
        end
      end
    end
  end
end
