# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared

      class GetHrisStaffingEntitiesPositiveResponseEmploymentType
        extend T::Sig
        include Crystalline::MetadataFields

        # The label of the employment type how it appears in the remote system.
        field :remote_label, ::String, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('remote_label'), required: true } }
        # The unified type, how Kombo categorize this label.
        field :unified_type, Crystalline::Nilable.new(Models::Shared::GetHrisStaffingEntitiesPositiveResponseUnifiedType), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('unified_type'), required: true, 'decoder': Utils.enum_from_string(Models::Shared::GetHrisStaffingEntitiesPositiveResponseUnifiedType, false) } }

        sig { params(remote_label: ::String, unified_type: T.nilable(Models::Shared::GetHrisStaffingEntitiesPositiveResponseUnifiedType)).void }
        def initialize(remote_label:, unified_type: nil)
          @remote_label = remote_label
          @unified_type = unified_type
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @remote_label == other.remote_label
          return false unless @unified_type == other.unified_type
          true
        end
      end
    end
  end
end
