# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared
      # The integration field the custom field is mapped to. Null if not mapped.
      class GetIntegrationsIntegrationIdCustomFieldsPositiveResponseIntegrationField
        extend T::Sig
        include Crystalline::MetadataFields

        # The integration field's unique ID
        field :id, ::String, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('id'), required: true } }
        # The key of the integration field in the remote system
        field :key, ::String, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('key'), required: true } }
        # The type of the integration field. There is a type to avoid collisions between DEFAULT fields and CUSTOM fields with the same key.
        field :type, Models::Shared::GetIntegrationsIntegrationIdCustomFieldsPositiveResponseType, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('type'), required: true, 'decoder': ::Kombo::Utils.enum_from_string(Models::Shared::GetIntegrationsIntegrationIdCustomFieldsPositiveResponseType, false) } }
        # The label of the integration field in the remote system
        field :label, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('label'), required: true } }

        sig { params(id: ::String, key: ::String, type: Models::Shared::GetIntegrationsIntegrationIdCustomFieldsPositiveResponseType, label: T.nilable(::String)).void }
        def initialize(id:, key:, type:, label: nil)
          @id = id
          @key = key
          @type = type
          @label = label
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @id == other.id
          return false unless @key == other.key
          return false unless @type == other.type
          return false unless @label == other.label
          true
        end
      end
    end
  end
end
