# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared

      class GetToolsCategoryPositiveResponseReadModelField
        extend T::Sig
        include Crystalline::MetadataFields

        # Key of the field in the model (e.g. first_name).
        field :id, ::String, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('id'), required: true } }
        # The status of a datapoint of an integrated tool:
        # 
        # - `SUPPORTED`: the tool supports the datapoint and it can be used through Kombo.
        # - `UNSUPPORTED`: the tool does not support the datapoint.
        # - `NOT_IMPLEMENTED`: tool supports the datapoint but it was not integrated by Kombo for a given reason (see coverage grid).
        # - `UNKNOWN`: the datapoint is not integrated yet and Kombo has no information about it's availability in the tool.
        field :coverage_status, Models::Shared::GetToolsCategoryPositiveResponseReadModelFieldCoverageStatus, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('coverage_status'), required: true, 'decoder': Utils.enum_from_string(Models::Shared::GetToolsCategoryPositiveResponseReadModelFieldCoverageStatus, false) } }

        sig { params(id: ::String, coverage_status: Models::Shared::GetToolsCategoryPositiveResponseReadModelFieldCoverageStatus).void }
        def initialize(id:, coverage_status:)
          @id = id
          @coverage_status = coverage_status
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @id == other.id
          return false unless @coverage_status == other.coverage_status
          true
        end
      end
    end
  end
end
