# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared
      # InlineAssessmentOrderReceivedWebhookPayloadStatus - The current status of the assessment order.
      class InlineAssessmentOrderReceivedWebhookPayloadStatus < T::Enum
        enums do
          OPEN = new('OPEN')
          COMPLETED = new('COMPLETED')
          CANCELLED = new('CANCELLED')
          REJECTED = new('REJECTED')
        end
      end
    end
  end
end
