# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared
      # InlineAssessmentOrderReceivedWebhookPayloadType - Type of the webhook event
      class InlineAssessmentOrderReceivedWebhookPayloadType < T::Enum
        enums do
          INLINE_ASSESSMENT_ORDER_RECEIVED = new('inline-assessment:order-received')
        end
      end
    end
  end
end
