# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared

      class IntegrationStateChangedWebhookPayloadData
        extend T::Sig
        include Crystalline::MetadataFields

        # The name of the integrated tool (e.g., "personio", "greenhouse").
        field :integration_tool, ::String, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('integration_tool'), required: true } }
        # The unique identifier of the integration.
        field :integration_id, ::String, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('integration_id'), required: true } }
        # The category of the integration (HRIS, ATS, ASSESSMENT, or LMS).
        field :integration_category, Models::Shared::IntegrationStateChangedWebhookPayloadIntegrationCategory, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('integration_category'), required: true, 'decoder': ::Kombo::Utils.enum_from_string(Models::Shared::IntegrationStateChangedWebhookPayloadIntegrationCategory, false) } }
        # Information about the end user who created the integration.
        field :end_user, Models::Shared::IntegrationStateChangedWebhookPayloadEndUser, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('end_user'), required: true } }
        # The quality assurance status of the integration.
        field :qa_status, Models::Shared::QaStatus, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('qa_status'), required: true, 'decoder': ::Kombo::Utils.enum_from_string(Models::Shared::QaStatus, false) } }
        # The current status of an integration that has filtering, field mapping features or required setup steps.
        field :setup_status, Models::Shared::IntegrationStateChangedWebhookPayloadSetupStatus, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('setup_status'), required: true, 'decoder': ::Kombo::Utils.enum_from_string(Models::Shared::IntegrationStateChangedWebhookPayloadSetupStatus, false) } }
        # The current state of the integration.
        field :state, Models::Shared::State, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('state'), required: true, 'decoder': ::Kombo::Utils.enum_from_string(Models::Shared::State, false) } }
        # ISO 8601 timestamp when the integration state was last updated.
        field :updated_at, ::DateTime, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('updated_at'), required: true, 'decoder': ::Kombo::Utils.datetime_from_iso_format(false) } }

        sig { params(integration_tool: ::String, integration_id: ::String, integration_category: Models::Shared::IntegrationStateChangedWebhookPayloadIntegrationCategory, end_user: Models::Shared::IntegrationStateChangedWebhookPayloadEndUser, qa_status: Models::Shared::QaStatus, setup_status: Models::Shared::IntegrationStateChangedWebhookPayloadSetupStatus, state: Models::Shared::State, updated_at: ::DateTime).void }
        def initialize(integration_tool:, integration_id:, integration_category:, end_user:, qa_status:, setup_status:, state:, updated_at:)
          @integration_tool = integration_tool
          @integration_id = integration_id
          @integration_category = integration_category
          @end_user = end_user
          @qa_status = qa_status
          @setup_status = setup_status
          @state = state
          @updated_at = updated_at
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @integration_tool == other.integration_tool
          return false unless @integration_id == other.integration_id
          return false unless @integration_category == other.integration_category
          return false unless @end_user == other.end_user
          return false unless @qa_status == other.qa_status
          return false unless @setup_status == other.setup_status
          return false unless @state == other.state
          return false unless @updated_at == other.updated_at
          true
        end
      end
    end
  end
end
