# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared

      class IntegrationDeletedWebhookPayloadData
        extend T::Sig
        include Crystalline::MetadataFields

        # The unique identifier of the deleted integration.
        field :id, ::String, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('id'), required: true } }
        # The name of the integrated tool.
        field :tool, ::String, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('tool'), required: true } }
        # The category of the integration.
        field :category, Models::Shared::IntegrationDeletedWebhookPayloadCategory, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('category'), required: true, 'decoder': ::Kombo::Utils.enum_from_string(Models::Shared::IntegrationDeletedWebhookPayloadCategory, false) } }
        # Information about the end user who created the integration.
        field :end_user, Models::Shared::IntegrationDeletedWebhookPayloadEndUser, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('end_user'), required: true } }
        # ISO 8601 timestamp when the integration was deleted.
        field :deleted_at, ::DateTime, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('deleted_at'), required: true, 'decoder': ::Kombo::Utils.datetime_from_iso_format(false) } }

        sig { params(id: ::String, tool: ::String, category: Models::Shared::IntegrationDeletedWebhookPayloadCategory, end_user: Models::Shared::IntegrationDeletedWebhookPayloadEndUser, deleted_at: ::DateTime).void }
        def initialize(id:, tool:, category:, end_user:, deleted_at:)
          @id = id
          @tool = tool
          @category = category
          @end_user = end_user
          @deleted_at = deleted_at
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @id == other.id
          return false unless @tool == other.tool
          return false unless @category == other.category
          return false unless @end_user == other.end_user
          return false unless @deleted_at == other.deleted_at
          true
        end
      end
    end
  end
end
