# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared
      # The integration this issue belongs to. `null` for environment-wide issues.
      class Integration
        extend T::Sig
        include Crystalline::MetadataFields

        # The unique identifier of the integration.
        field :id, ::String, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('id'), required: true } }
        # The name of the integrated tool (e.g., "personio", "greenhouse").
        field :tool, ::String, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('tool'), required: true } }
        # The category of the integration (HRIS, ATS, ASSESSMENT, or LMS).
        field :category, Models::Shared::IssueStatusChangedWebhookPayloadCategory, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('category'), required: true, 'decoder': ::Kombo::Utils.enum_from_string(Models::Shared::IssueStatusChangedWebhookPayloadCategory, false) } }
        # Information about the end user who created the integration.
        field :end_user, Models::Shared::IssueStatusChangedWebhookPayloadEndUser, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('end_user'), required: true } }

        sig { params(id: ::String, tool: ::String, category: Models::Shared::IssueStatusChangedWebhookPayloadCategory, end_user: Models::Shared::IssueStatusChangedWebhookPayloadEndUser).void }
        def initialize(id:, tool:, category:, end_user:)
          @id = id
          @tool = tool
          @category = category
          @end_user = end_user
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @id == other.id
          return false unless @tool == other.tool
          return false unless @category == other.category
          return false unless @end_user == other.end_user
          true
        end
      end
    end
  end
end
