# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared
      # IssueStatusChangedWebhookPayloadStatus - The issue status after this change.
      class IssueStatusChangedWebhookPayloadStatus < T::Enum
        enums do
          OPEN = new('OPEN')
          RESOLVED = new('RESOLVED')
        end
      end
    end
  end
end
