# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared

      class JobPostingVisibility < T::Enum
        enums do
          PUBLIC = new('PUBLIC')
          INTERNAL = new('INTERNAL')
          UNLISTED = new('UNLISTED')
        end
      end
    end
  end
end
