# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared

      class JobPosting
        extend T::Sig
        include Crystalline::MetadataFields

        # The globally unique ID of this object generated by Kombo. We recommend using this as a stable primary key for syncing.
        field :id, ::String, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('id'), required: true } }
        # The raw ID of the object in the remote system. We don't recommend using this as a primary key on your side as it might sometimes be compromised of multiple identifiers if a system doesn't provide a clear primary key.
        field :remote_id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('remote_id'), required: true } }
        # The job posting’s title.
        field :title, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('title'), required: true } }
        # The job posting’s description in HTML format.
        field :description_html, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('description_html'), required: true } }
        # The job posting’s current status.
        field :status, Crystalline::Nilable.new(Models::Shared::JobPostingStatus), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('status'), required: true, 'decoder': ::Kombo::Utils.enum_from_string(Models::Shared::JobPostingStatus, false) } }

        field :visibility, Crystalline::Nilable.new(Models::Shared::JobPostingVisibility), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('visibility'), required: true, 'decoder': ::Kombo::Utils.enum_from_string(Models::Shared::JobPostingVisibility, false) } }
        # The public URL to the job posting on the ATS platform.
        field :url, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('url'), required: true } }

        sig { params(id: ::String, remote_id: T.nilable(::String), title: T.nilable(::String), description_html: T.nilable(::String), status: T.nilable(Models::Shared::JobPostingStatus), visibility: T.nilable(Models::Shared::JobPostingVisibility), url: T.nilable(::String)).void }
        def initialize(id:, remote_id: nil, title: nil, description_html: nil, status: nil, visibility: nil, url: nil)
          @id = id
          @remote_id = remote_id
          @title = title
          @description_html = description_html
          @status = status
          @visibility = visibility
          @url = url
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @id == other.id
          return false unless @remote_id == other.remote_id
          return false unless @title == other.title
          return false unless @description_html == other.description_html
          return false unless @status == other.status
          return false unless @visibility == other.visibility
          return false unless @url == other.url
          true
        end
      end
    end
  end
end
