# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared
      # KomboHrisErrorCode - Some errors include an error code that can be used to identify their cause. See the [Error Handling Docs](https://docs.kombo.dev/guides/errors) for more information. For your error handling logic please use the error `code` instead of other properties (e.g. message, http status code, ...).
      class KomboHrisErrorCode < T::Enum
        enums do
          PLATFORM_RATE_LIMIT_EXCEEDED = new('PLATFORM.RATE_LIMIT_EXCEEDED')
          PLATFORM_INTEGRATION_NOT_FOUND = new('PLATFORM.INTEGRATION_NOT_FOUND')
          PLATFORM_INPUT_INVALID = new('PLATFORM.INPUT_INVALID')
          PLATFORM_UNKNOWN_ERROR = new('PLATFORM.UNKNOWN_ERROR')
          PLATFORM_IP_NOT_WHITELISTED = new('PLATFORM.IP_NOT_WHITELISTED')
          PLATFORM_AUTHENTICATION_INVALID = new('PLATFORM.AUTHENTICATION_INVALID')
          PLATFORM_TASK_TIMED_OUT = new('PLATFORM.TASK_TIMED_OUT')
          INTEGRATION_PERMISSION_MISSING = new('INTEGRATION.PERMISSION_MISSING')
          INTEGRATION_AUTHENTICATION_INVALID = new('INTEGRATION.AUTHENTICATION_INVALID')
          INTEGRATION_QA_FAILED = new('INTEGRATION.QA_FAILED')
          INTEGRATION_SETUP_SYNC_PENDING = new('INTEGRATION.SETUP_SYNC_PENDING')
          INTEGRATION_SETUP_INCOMPLETE = new('INTEGRATION.SETUP_INCOMPLETE')
          INTEGRATION_INACTIVE = new('INTEGRATION.INACTIVE')
          INTEGRATION_MODEL_NOT_AVAILABLE = new('INTEGRATION.MODEL_NOT_AVAILABLE')
          INTEGRATION_MODEL_DISABLED = new('INTEGRATION.MODEL_DISABLED')
          INTEGRATION_ACTION_NOT_AVAILABLE = new('INTEGRATION.ACTION_NOT_AVAILABLE')
          INTEGRATION_ACTION_DISABLED = new('INTEGRATION.ACTION_DISABLED')
          REMOTE_SERVICE_UNAVAILABLE = new('REMOTE.SERVICE_UNAVAILABLE')
          REMOTE_RATE_LIMIT_EXCEEDED = new('REMOTE.RATE_LIMIT_EXCEEDED')
          REMOTE_INPUT_INVALID = new('REMOTE.INPUT_INVALID')
          REMOTE_UNKNOWN_HTTP_ERROR = new('REMOTE.UNKNOWN_HTTP_ERROR')
          HRIS_EMPLOYEE_ALREADY_EXISTS = new('HRIS.EMPLOYEE_ALREADY_EXISTS')
        end
      end
    end
  end
end
