# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared
      # Method - The HTTP method (e.g., `GET`) of the request.
      class Method < T::Enum


        enums do
          GET = new('GET')
          POST = new('POST')
          DELETE = new('DELETE')
          PUT = new('PUT')
          PATCH = new('PATCH')
        end
      end
    end
  end
end
