# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared
      # Name - The name of the Kombo model or connection that changed.
      class Name < T::Enum


        enums do
          HRIS_LEGAL_ENTITIES = new('hris_legal_entities')
          HRIS_LOCATIONS = new('hris_locations')
          HRIS_EMPLOYEES = new('hris_employees')
          HRIS_ABSENCE_TYPES = new('hris_absence_types')
          HRIS_ABSENCES = new('hris_absences')
          HRIS_EMPLOYMENTS = new('hris_employments')
          HRIS_TEAMS = new('hris_teams')
          HRIS_TIME_OFF_BALANCES = new('hris_time_off_balances')
          HRIS_TIMESHEETS = new('hris_timesheets')
          HRIS_EMPLOYEE_DOCUMENT_CATEGORIES = new('hris_employee_document_categories')
          HRIS_PERFORMANCE_REVIEWS = new('hris_performance_reviews')
          HRIS_PERFORMANCE_REVIEW_CYCLES = new('hris_performance_review_cycles')
          HRIS_STAFFING_ENTITIES = new('hris_staffing_entities')
          ATS_USERS = new('ats_users')
          ATS_JOBS = new('ats_jobs')
          ATS_JOB_POSTINGS = new('ats_job_postings')
          ATS_CANDIDATES = new('ats_candidates')
          ATS_APPLICATION_STAGES = new('ats_application_stages')
          ATS_APPLICATIONS = new('ats_applications')
          ATS_SCREENING_QUESTIONS = new('ats_screening_questions')
          ATS_TAGS = new('ats_tags')
          ATS_INTERVIEWS = new('ats_interviews')
          ATS_OFFERS = new('ats_offers')
          ATS_REJECTION_REASONS = new('ats_rejection_reasons')
          ATS_ROLES = new('ats_roles')
          LMS_USERS = new('lms_users')
          LMS_COURSE_PROVIDERS = new('lms_course_providers')
          LMS_SKILLS = new('lms_skills')
          LMS_COURSES = new('lms_courses')
          LMS_COURSE_REVISIONS = new('lms_course_revisions')
          LMS_COURSE_PROGRESSIONS = new('lms_course_progressions')
          HRIS_JOIN_EMPLOYEES_TEAMS = new('hris_join_employees_teams')
          HRIS_JOIN_STAFFING_ENTITIES_LOCATIONS = new('hris_join_staffing_entities_locations')
          HRIS_JOIN_STAFFING_ENTITIES_LEGAL_ENTITIES = new('hris_join_staffing_entities_legal_entities')
          HRIS_JOIN_STAFFING_ENTITIES_GROUPS = new('hris_join_staffing_entities_groups')
          ATS_JOIN_CANDIDATES_TAGS = new('ats_join_candidates_tags')
          ATS_JOIN_JOBS_APPLICATION_STAGES = new('ats_join_jobs_application_stages')
          ATS_JOIN_JOBS_SCREENING_QUESTIONS = new('ats_join_jobs_screening_questions')
          ATS_JOIN_USER_JOB_ROLE_ASSIGNMENTS = new('ats_join_user_job_role_assignments')
          ATS_JOIN_JOBS_USERS = new('ats_join_jobs_users')
          ATS_JOIN_USERS_ROLES = new('ats_join_users_roles')
          ATS_JOIN_INTERVIEWS_USERS = new('ats_join_interviews_users')
          LMS_JOIN_REVISIONS_SKILLS = new('lms_join_revisions_skills')
        end
      end
    end
  end
end
