# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared

      class OrderedOption
        extend T::Sig
        include Crystalline::MetadataFields

        # The Kombo ID of this proficiency option. Submit this ID when writing a rating for a `SINGLE_SELECT` skill.
        field :id, ::String, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('id'), required: true } }
        # The display name of this proficiency level.
        field :name, ::String, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('name'), required: true } }
        # The ID of this option in the remote system. `null` when the system identifies the level only by its name.
        field :remote_id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('remote_id'), required: true } }

        sig { params(id: ::String, name: ::String, remote_id: T.nilable(::String)).void }
        def initialize(id:, name:, remote_id: nil)
          @id = id
          @name = name
          @remote_id = remote_id
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @id == other.id
          return false unless @name == other.name
          return false unless @remote_id == other.remote_id
          true
        end
      end
    end
  end
end
