# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared
      # The pay run the payslip was paid out through.
      class PayRun
        extend T::Sig
        include Crystalline::MetadataFields

        # The globally unique ID of this object generated by Kombo. We recommend using this as a stable primary key for syncing.
        field :id, ::String, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('id'), required: true } }
        # The raw ID of the object in the remote system. We don't recommend using this as a primary key on your side as it might sometimes be compromised of multiple identifiers if a system doesn't provide a clear primary key.
        field :remote_id, ::String, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('remote_id'), required: true } }
        # The start date of the pay run, as a calendar date (`yyyy-MM-dd`).
        field :start_date, Crystalline::Nilable.new(::Date), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('start_date'), required: true, 'decoder': ::Kombo::Utils.date_from_iso_format(false) } }
        # The end date of the pay run, as a calendar date (`yyyy-MM-dd`).
        field :end_date, Crystalline::Nilable.new(::Date), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('end_date'), required: true, 'decoder': ::Kombo::Utils.date_from_iso_format(false) } }
        # The Kombo ID of the pay run’s legal entity. The ID can be used to retrieve the legal entity from the `get legal entities` endpoint.
        field :legal_entity_id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('legal_entity_id'), required: true } }

        sig { params(id: ::String, remote_id: ::String, start_date: T.nilable(::Date), end_date: T.nilable(::Date), legal_entity_id: T.nilable(::String)).void }
        def initialize(id:, remote_id:, start_date: nil, end_date: nil, legal_entity_id: nil)
          @id = id
          @remote_id = remote_id
          @start_date = start_date
          @end_date = end_date
          @legal_entity_id = legal_entity_id
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @id == other.id
          return false unless @remote_id == other.remote_id
          return false unless @start_date == other.start_date
          return false unless @end_date == other.end_date
          return false unless @legal_entity_id == other.legal_entity_id
          true
        end
      end
    end
  end
end
