# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared
      # Answer to a question. This will be validated based on the question format and throw an error if the answer is invalid. Here is a description of each question type and the required answer format:
      #
      # `TEXT` - Simply provide a "string" answer.
      #
      # `SINGLE_SELECT` - Provide the ID of the answer as a string.
      #
      # `MULTI_SELECT` - Provide a string array containing the question IDs of the selected options.
      #
      # `BOOLEAN` - Either `true` or `false`.
      #
      # `NUMBER` - A number.
      #
      # `DATE` - Provide the answer as an ISO 8601 date string.
      #
      # `FILE` - Please select Option 6 in the dropdown above to see the required format.
      class PostAtsCandidatesRequestBodyAnswerUnion
        extend T::Sig
        include Crystalline::MetadataFields


        
        def initialize; end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          true
        end
      end
    end
  end
end
