# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared
      # Fields specific to Greenhouse V3 (OAuth-based connector).
      class PostAtsJobsJobIdApplicationsRequestBodyGreenhousev3
        extend T::Sig
        include Crystalline::MetadataFields

        # Additional fields passed through to Greenhouse V3's `POST /v3/candidates` request body.
        field :candidate, Crystalline::Nilable.new(Crystalline::Hash.new(Symbol, ::Object)), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('candidate') } }
        # Additional fields passed through to Greenhouse V3's `POST /v3/applications` request body.
        field :application, Crystalline::Nilable.new(Crystalline::Hash.new(Symbol, ::Object)), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('application') } }

        sig { params(candidate: T.nilable(T::Hash[Symbol, ::Object]), application: T.nilable(T::Hash[Symbol, ::Object])).void }
        def initialize(candidate: nil, application: nil)
          @candidate = candidate
          @application = application
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @candidate == other.candidate
          return false unless @application == other.application
          true
        end
      end
    end
  end
end
