# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared
      # Lever specific remote fields for the note.
      class PostAtsApplicationsApplicationIdNotesRequestBodyLever
        extend T::Sig
        include Crystalline::MetadataFields

        # ID of the Lever user that will show up as having created the note. If not provided, defaults to the user associated with the OAuth token.
        field :perform_as, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('perform_as') } }

        sig { params(perform_as: T.nilable(::String)).void }
        def initialize(perform_as: nil)
          @perform_as = perform_as
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @perform_as == other.perform_as
          true
        end
      end
    end
  end
end
