# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared
      # PostHrisAbsencesRequestBodyStatus - The state that the absence should be created in. Some tools may approve absences automatically if they were created for an absence type that does not require approval.
      class PostHrisAbsencesRequestBodyStatus < T::Enum
        enums do
          REQUESTED = new('REQUESTED')
          APPROVED = new('APPROVED')
        end
      end
    end
  end
end
