# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared

      class PostHrisAbsencesPositiveResponseData
        extend T::Sig
        include Crystalline::MetadataFields

        # The globally unique ID of this object generated by Kombo. We recommend using this as a stable primary key for syncing.
        field :id, ::String, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('id'), required: true } }
        # The Kombo ID of the employee to which the absence belongs to. The ID can be used to retrieve the employee from the `get employees` endpoint.
        field :employee_id, ::String, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('employee_id'), required: true } }
        # The timestamp when this specific record was last modified. This field only updates when properties directly on this record change, NOT when related or nested models change. For filtering that considers nested data changes, use the `updated_after` parameter which will return records when either the record itself OR its related models have been updated.
        # https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString
        field :changed_at, ::DateTime, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('changed_at'), required: true, 'decoder': Utils.datetime_from_iso_format(false) } }
        # The raw ID of the object in the remote system. We don't recommend using this as a primary key on your side as it might sometimes be compromised of multiple identifiers if a system doesn't provide a clear primary key.
        field :remote_id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('remote_id'), required: true } }
        # The date this absence starts in the `yyyy-MM-dd` format.
        field :start_date, Crystalline::Nilable.new(::Object), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('start_date'), required: true } }
        # The date this absence ends in the `yyyy-MM-dd` format.
        field :end_date, Crystalline::Nilable.new(::Object), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('end_date'), required: true } }
        # `true` if the absence starts in the middle of the day, `false` if not, and `null` if the absence type doesn't support half-day absences. For multi-day absences, this only applies to the first day of the absence.
        field :start_half_day, Crystalline::Nilable.new(Crystalline::Boolean.new), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('start_half_day'), required: true } }
        # `true` if the absence ends in the middle of the day, `false` if not, and `null` if the absence type doesn't support half-day absences. For multi-day absences, this only applies to the last day of the absence.
        field :end_half_day, Crystalline::Nilable.new(Crystalline::Boolean.new), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('end_half_day'), required: true } }
        # The time at which this absence starts. Follows the format `HH:mm:ss` (e.g., `14:45:15`).
        field :start_time, Crystalline::Nilable.new(::Object), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('start_time'), required: true } }
        # The time at which this absence ends. Follows the format `HH:mm:ss` (e.g., `14:45:15`).
        field :end_time, Crystalline::Nilable.new(::Object), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('end_time'), required: true } }
        # The amount of time this absence takes.
        field :amount, Crystalline::Nilable.new(::Float), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('amount'), required: true } }
        # The unit of time for this absence. Can be `HOURS` or `DAYS`.
        field :unit, Crystalline::Nilable.new(Models::Shared::PostHrisAbsencesPositiveResponseUnit), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('unit'), required: true, 'decoder': Utils.enum_from_string(Models::Shared::PostHrisAbsencesPositiveResponseUnit, false) } }
        # A note the employee has added to this absence.
        field :employee_note, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('employee_note'), required: true } }
        # The Kombo absence type ID of this absence.
        field :type_id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('type_id'), required: true } }
        # The date and time the object was deleted in the remote system. Objects are automatically marked as deleted when Kombo can't retrieve them from the remote system anymore. Kombo will also anonymize entries 14 days after they disappear.
        # https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString
        field :remote_deleted_at, Crystalline::Nilable.new(::DateTime), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('remote_deleted_at'), required: true, 'decoder': Utils.datetime_from_iso_format(false) } }
        # The absence’s current status. In rare cases where we can’t find a clear mapping, the original string is passed through.
        field :status, Crystalline::Nilable.new(Models::Shared::PostHrisAbsencesPositiveResponseStatus), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('status'), 'decoder': Utils.open_enum_from_string(Models::Shared::PostHrisAbsencesPositiveResponseStatus, true) } }

        sig { params(id: ::String, employee_id: ::String, changed_at: ::DateTime, remote_id: T.nilable(::String), start_date: T.nilable(::Object), end_date: T.nilable(::Object), start_half_day: T.nilable(T::Boolean), end_half_day: T.nilable(T::Boolean), start_time: T.nilable(::Object), end_time: T.nilable(::Object), amount: T.nilable(::Float), unit: T.nilable(Models::Shared::PostHrisAbsencesPositiveResponseUnit), employee_note: T.nilable(::String), type_id: T.nilable(::String), remote_deleted_at: T.nilable(::DateTime), status: T.nilable(Models::Shared::PostHrisAbsencesPositiveResponseStatus)).void }
        def initialize(id:, employee_id:, changed_at:, remote_id: nil, start_date: nil, end_date: nil, start_half_day: nil, end_half_day: nil, start_time: nil, end_time: nil, amount: nil, unit: nil, employee_note: nil, type_id: nil, remote_deleted_at: nil, status: nil)
          @id = id
          @employee_id = employee_id
          @changed_at = changed_at
          @remote_id = remote_id
          @start_date = start_date
          @end_date = end_date
          @start_half_day = start_half_day
          @end_half_day = end_half_day
          @start_time = start_time
          @end_time = end_time
          @amount = amount
          @unit = unit
          @employee_note = employee_note
          @type_id = type_id
          @remote_deleted_at = remote_deleted_at
          @status = status
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @id == other.id
          return false unless @employee_id == other.employee_id
          return false unless @changed_at == other.changed_at
          return false unless @remote_id == other.remote_id
          return false unless @start_date == other.start_date
          return false unless @end_date == other.end_date
          return false unless @start_half_day == other.start_half_day
          return false unless @end_half_day == other.end_half_day
          return false unless @start_time == other.start_time
          return false unless @end_time == other.end_time
          return false unless @amount == other.amount
          return false unless @unit == other.unit
          return false unless @employee_note == other.employee_note
          return false unless @type_id == other.type_id
          return false unless @remote_deleted_at == other.remote_deleted_at
          return false unless @status == other.status
          true
        end
      end
    end
  end
end
