# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared
      # Fields specific to Traffit.
      class PostAtsApplicationsApplicationIdResultLinksRequestBodyTraffit
        extend T::Sig
        include Crystalline::MetadataFields

        # Fields that we will write to the Traffit candidate before adding the result note. Custom fields are keyed by their SID with a `_` prefix, for example `{ "_Assessment_Score": "5" }`. The field must be available via integration in Traffit.
        field :candidate, Crystalline::Nilable.new(Crystalline::Hash.new(Symbol, ::Object)), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('candidate') } }

        sig { params(candidate: T.nilable(T::Hash[Symbol, ::Object])).void }
        def initialize(candidate: nil)
          @candidate = candidate
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @candidate == other.candidate
          true
        end
      end
    end
  end
end
