# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared
      # PostAtsJobsJobIdApplicationsRequestBodyGender - The gender of the candidate. Must be one of `MALE`, `FEMALE`, or `OTHER`.
      class PostAtsJobsJobIdApplicationsRequestBodyGender < T::Enum
        enums do
          MALE = new('MALE')
          FEMALE = new('FEMALE')
          OTHER = new('OTHER')
        end
      end
    end
  end
end
