# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared
      # Additional fields that we will pass through to specific HRIS systems.
      class PostHrisEmployeesEmployeeIdDocumentsRequestBodyRemoteFields
        extend T::Sig
        include Crystalline::MetadataFields

        # Fields specific to AFAS.
        field :afas, Crystalline::Nilable.new(Models::Shared::Afas), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('afas') } }

        sig { params(afas: T.nilable(Models::Shared::Afas)).void }
        def initialize(afas: nil)
          @afas = afas
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @afas == other.afas
          true
        end
      end
    end
  end
end
