# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared

      class PostAtsJobsJobIdApplicationsPositiveResponseQuestionText
        extend T::Sig
        include Crystalline::MetadataFields


        field :title, ::String, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('title'), required: true } }

        field :remote_id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('remote_id'), required: true } }

        field :type, ::String, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('type'), required: true } }

        sig { params(title: ::String, remote_id: T.nilable(::String), type: ::String).void }
        def initialize(title:, remote_id: nil, type: 'TEXT')
          @title = title
          @remote_id = remote_id
          unless type == 'TEXT'
            raise ArgumentError, 'Invalid value for type'
          end
          @type = 'TEXT'
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @title == other.title
          return false unless @remote_id == other.remote_id
          return false unless @type == other.type
          true
        end
      end
    end
  end
end
