# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared
      # PostAtsCandidatesCandidateIdAttachmentsRequestBodyType - Type of the attachment in the ATS. This may affect where the uploaded file will be shown in your customer's system.
      class PostAtsCandidatesCandidateIdAttachmentsRequestBodyType < T::Enum
        enums do
          CV = new('CV')
          COVER_LETTER = new('COVER_LETTER')
          OTHER = new('OTHER')
        end
      end
    end
  end
end
