# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared
      # The WID of the social suffix reference for the candidate
      class PostAtsCandidatesRequestBodySocialSuffixReference
        extend T::Sig
        include Crystalline::MetadataFields


        field :predefined_name_component_id, ::String, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('Predefined_Name_Component_ID'), required: true } }

        sig { params(predefined_name_component_id: ::String).void }
        def initialize(predefined_name_component_id:)
          @predefined_name_component_id = predefined_name_component_id
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @predefined_name_component_id == other.predefined_name_component_id
          true
        end
      end
    end
  end
end
