# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared
      # Additional candidate fields for P&I Loga that will be mapped to the application form.
      class PostAtsJobsJobIdApplicationsRequestBodyPilogaCandidate
        extend T::Sig
        include Crystalline::MetadataFields

        # The street address of the candidate.
        field :street, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('street') } }
        # The birth date of the candidate, written into the "Geburtsdatum" field of the application form. Format: `YYYY-MM-DD`
        # https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString
        field :geburtsdatum, Crystalline::Nilable.new(::DateTime), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('geburtsdatum'), 'decoder': ::Kombo::Utils.datetime_from_iso_format(true) } }

        sig { params(street: T.nilable(::String), geburtsdatum: T.nilable(::DateTime)).void }
        def initialize(street: nil, geburtsdatum: nil)
          @street = street
          @geburtsdatum = geburtsdatum
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @street == other.street
          return false unless @geburtsdatum == other.geburtsdatum
          true
        end
      end
    end
  end
end
