# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared
      # Greenhouse V3 specific remote fields for the note.
      class PostAtsApplicationsApplicationIdNotesRequestBodyGreenhousev3
        extend T::Sig
        include Crystalline::MetadataFields

        # Visibility of the created note.
        field :visibility, Crystalline::Nilable.new(Models::Shared::PostAtsApplicationsApplicationIdNotesRequestBodyVisibility), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('visibility'), 'decoder': Utils.enum_from_string(Models::Shared::PostAtsApplicationsApplicationIdNotesRequestBodyVisibility, true) } }

        sig { params(visibility: T.nilable(Models::Shared::PostAtsApplicationsApplicationIdNotesRequestBodyVisibility)).void }
        def initialize(visibility: nil)
          @visibility = visibility
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @visibility == other.visibility
          true
        end
      end
    end
  end
end
