# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared

      class PostAtsImportTrackedApplicationPositiveResponseSuccessfactorsApplicationRemoteID
        extend T::Sig
        include Crystalline::MetadataFields


        field :application_remote_id, ::String, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('application_remote_id'), required: true } }
        # Uses the `/JobApplication` ODATA endpoint to retrieve the relevant application based on the application ID.
        field :id_type, ::String, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('id_type'), required: true } }

        sig { params(application_remote_id: ::String, id_type: ::String).void }
        def initialize(application_remote_id:, id_type: 'application_remote_id')
          @application_remote_id = application_remote_id
          unless id_type == 'application_remote_id'
            raise ArgumentError, 'Invalid value for id_type'
          end
          @id_type = 'application_remote_id'
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @application_remote_id == other.application_remote_id
          return false unless @id_type == other.id_type
          true
        end
      end
    end
  end
end
