# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared

      class PostAtsCandidatesRequestBodyCustomField
        extend T::Sig
        include Crystalline::MetadataFields

        # ID of the Recruit CRM candidate custom field (`GET /v1/custom-fields/candidates`).
        field :field_id, ::Integer, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('field_id'), required: true } }
        # Value to write. Dropdown and multiselect values must match a configured option. File fields take a direct download URL.
        field :value, ::String, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('value'), required: true } }
        # Entity the custom field belongs to, usually `candidate`.
        field :entity_type, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('entity_type') } }
        # Custom field name.
        field :field_name, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('field_name') } }
        # Custom field type, for example `text`.
        field :field_type, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('field_type') } }

        sig { params(field_id: ::Integer, value: ::String, entity_type: T.nilable(::String), field_name: T.nilable(::String), field_type: T.nilable(::String)).void }
        def initialize(field_id:, value:, entity_type: nil, field_name: nil, field_type: nil)
          @field_id = field_id
          @value = value
          @entity_type = entity_type
          @field_name = field_name
          @field_type = field_type
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @field_id == other.field_id
          return false unless @value == other.value
          return false unless @entity_type == other.entity_type
          return false unless @field_name == other.field_name
          return false unless @field_type == other.field_type
          true
        end
      end
    end
  end
end
