# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared
      # PostAtsJobsJobIdApplicationsRequestBodyPeriod - The period of the salary expectations. Must be one of `MONTH` or `YEAR`.
      class PostAtsJobsJobIdApplicationsRequestBodyPeriod < T::Enum
        enums do
          MONTH = new('MONTH')
          YEAR = new('YEAR')
        end
      end
    end
  end
end
