# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared

      class PostHrisAbsencesPositiveResponse
        extend T::Sig
        include Crystalline::MetadataFields


        field :status, ::String, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('status'), required: true } }

        field :data, Models::Shared::PostHrisAbsencesPositiveResponseData, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('data'), required: true } }
        # These are the interaction warnings that are shown in the dashboard. They are meant to provide debug information to you. We recommend logging them to the console.
        field :warnings, Crystalline::Array.new(Models::Shared::PostHrisAbsencesPositiveResponseWarning), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('warnings'), required: true } }

        sig { params(status: ::String, data: Models::Shared::PostHrisAbsencesPositiveResponseData, warnings: T::Array[Models::Shared::PostHrisAbsencesPositiveResponseWarning]).void }
        def initialize(status:, data:, warnings:)
          unless status == 'success'
            raise ArgumentError, 'Invalid value for status'
          end
          @status = 'success'
          @data = data
          @warnings = warnings
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @status == other.status
          return false unless @data == other.data
          return false unless @warnings == other.warnings
          true
        end
      end
    end
  end
end
