# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared

      class PostAtsImportTrackedApplicationRequestBodySmartrecruitersCandidateAndJobRemoteIds
        extend T::Sig
        include Crystalline::MetadataFields


        field :candidate_remote_id, ::String, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('candidate_remote_id'), required: true } }

        field :job_remote_id, ::String, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('job_remote_id'), required: true } }
        # Uses the `/candidates/{candidateId}/jobs/{jobId}` endpoint to retrieve the application.
        field :id_type, ::String, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('id_type'), required: true } }

        sig { params(candidate_remote_id: ::String, job_remote_id: ::String, id_type: ::String).void }
        def initialize(candidate_remote_id:, job_remote_id:, id_type: 'candidate_and_job_remote_ids')
          @candidate_remote_id = candidate_remote_id
          @job_remote_id = job_remote_id
          unless id_type == 'candidate_and_job_remote_ids'
            raise ArgumentError, 'Invalid value for id_type'
          end
          @id_type = 'candidate_and_job_remote_ids'
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @candidate_remote_id == other.candidate_remote_id
          return false unless @job_remote_id == other.job_remote_id
          return false unless @id_type == other.id_type
          true
        end
      end
    end
  end
end
