# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared

      class PostAtsImportTrackedApplicationRequestBodyOnlyfyApplicationID
        extend T::Sig
        include Crystalline::MetadataFields


        field :application_id, ::String, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('application_id'), required: true } }
        # Uses the `/v1/application/{id}` endpoint to retrieve the application.
        field :id_type, ::String, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('id_type'), required: true } }

        sig { params(application_id: ::String, id_type: ::String).void }
        def initialize(application_id:, id_type: 'application_id')
          @application_id = application_id
          unless id_type == 'application_id'
            raise ArgumentError, 'Invalid value for id_type'
          end
          @id_type = 'application_id'
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @application_id == other.application_id
          return false unless @id_type == other.id_type
          true
        end
      end
    end
  end
end
