# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared

      class PostForceSyncRequestBody
        extend T::Sig
        include Crystalline::MetadataFields

        # The type of the triggered sync.
        field :type, Crystalline::Nilable.new(Models::Shared::PostForceSyncRequestBodyType), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('type'), 'decoder': ::Kombo::Utils.enum_from_string(Models::Shared::PostForceSyncRequestBodyType, true) } }

        sig { params(type: T.nilable(Models::Shared::PostForceSyncRequestBodyType)).void }
        def initialize(type: Models::Shared::PostForceSyncRequestBodyType::FULL)
          @type = type
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @type == other.type
          true
        end
      end
    end
  end
end
