# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared

      class PostHrisAbsencesPositiveResponseStatus
        include ::Crystalline::Enum
        enums do
          REQUESTED = new('REQUESTED')
          APPROVED = new('APPROVED')
          DECLINED = new('DECLINED')
          CANCELLED = new('CANCELLED')
          DELETED = new('DELETED')
        end
        open!
      end
    end
  end
end
