# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared

      class ProficiencyScaleNumeric
        extend T::Sig
        include Crystalline::MetadataFields

        # The globally unique ID of this object generated by Kombo. We recommend using this as a stable primary key for syncing.
        field :id, ::String, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('id'), required: true } }
        # The raw ID of the object in the remote system. We don't recommend using this as a primary key on your side as it might sometimes be compromised of multiple identifiers if a system doesn't provide a clear primary key.
        field :remote_id, ::String, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('remote_id'), required: true } }

        field :type, ::String, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('type'), required: true } }
        # The lowest value of the proficiency scale.
        field :min, Crystalline::Nilable.new(::Float), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('min'), required: true } }
        # The highest value of the proficiency scale.
        field :max, Crystalline::Nilable.new(::Float), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('max'), required: true } }
        # The increment between valid values – `1` for an integer scale, a fractional value (e.g. `0.1`) for finer scales, `null` for a continuous scale with no fixed step.
        field :step, Crystalline::Nilable.new(::Float), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('step'), required: true } }

        sig { params(id: ::String, remote_id: ::String, type: ::String, min: T.nilable(::Float), max: T.nilable(::Float), step: T.nilable(::Float)).void }
        def initialize(id:, remote_id:, type: 'NUMERIC', min: nil, max: nil, step: nil)
          @id = id
          @remote_id = remote_id
          unless type == 'NUMERIC'
            raise ArgumentError, 'Invalid value for type'
          end
          @type = 'NUMERIC'
          @min = min
          @max = max
          @step = step
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @id == other.id
          return false unless @remote_id == other.remote_id
          return false unless @type == other.type
          return false unless @min == other.min
          return false unless @max == other.max
          return false unless @step == other.step
          true
        end
      end
    end
  end
end
