# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared

      class ProficiencyScaleSingleSelect
        extend T::Sig
        include Crystalline::MetadataFields

        # The globally unique ID of this object generated by Kombo. We recommend using this as a stable primary key for syncing.
        field :id, ::String, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('id'), required: true } }
        # The raw ID of the object in the remote system. We don't recommend using this as a primary key on your side as it might sometimes be compromised of multiple identifiers if a system doesn't provide a clear primary key.
        field :remote_id, ::String, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('remote_id'), required: true } }
        # The available proficiency levels, ordered from lowest to highest.
        field :ordered_options, Crystalline::Array.new(Models::Shared::OrderedOption), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('ordered_options'), required: true } }

        field :type, ::String, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('type'), required: true } }

        sig { params(id: ::String, remote_id: ::String, ordered_options: T::Array[Models::Shared::OrderedOption], type: ::String).void }
        def initialize(id:, remote_id:, ordered_options:, type: 'SINGLE_SELECT')
          @id = id
          @remote_id = remote_id
          @ordered_options = ordered_options
          unless type == 'SINGLE_SELECT'
            raise ArgumentError, 'Invalid value for type'
          end
          @type = 'SINGLE_SELECT'
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @id == other.id
          return false unless @remote_id == other.remote_id
          return false unless @ordered_options == other.ordered_options
          return false unless @type == other.type
          true
        end
      end
    end
  end
end
