# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared

      class PutAtsApplicationsApplicationIdStageRequestBody
        extend T::Sig
        include Crystalline::MetadataFields

        # The Kombo ID of the stage to move the application to. This stage must be allowed for the job that the application is connected to. Get available stages from the `stages` property on the job, not from the deprecated application-stages endpoint.
        field :stage_id, ::String, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('stage_id'), required: true } }
        # Additional fields that we will pass through to specific ATS systems.
        field :remote_fields, Crystalline::Nilable.new(Models::Shared::PutAtsApplicationsApplicationIdStageRequestBodyRemoteFields), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('remote_fields') } }

        sig { params(stage_id: ::String, remote_fields: T.nilable(Models::Shared::PutAtsApplicationsApplicationIdStageRequestBodyRemoteFields)).void }
        def initialize(stage_id:, remote_fields: nil)
          @stage_id = stage_id
          @remote_fields = remote_fields
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @stage_id == other.stage_id
          return false unless @remote_fields == other.remote_fields
          true
        end
      end
    end
  end
end
