# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared
      # Fields specific to Workday's `Assess_Candidate` [operation](https://community.workday.com/sites/default/files/file-hosting/productionapi/Recruiting/v46.0/Assess_Candidate.html).
      class PutAssessmentOrdersAssessmentOrderIdResultRequestBodyWorkday
        extend T::Sig
        include Crystalline::MetadataFields

        # References to the Candidate Assessment to be created or modified along with the data to be used in the creation or modification.
        field :assess_candidate_data, Crystalline::Nilable.new(Models::Shared::AssessCandidateData), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('Assess_Candidate_Data') } }

        sig { params(assess_candidate_data: T.nilable(Models::Shared::AssessCandidateData)).void }
        def initialize(assess_candidate_data: nil)
          @assess_candidate_data = assess_candidate_data
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @assess_candidate_data == other.assess_candidate_data
          true
        end
      end
    end
  end
end
