# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared
      # Additional fields that we will pass through to specific ATS systems.
      class PutAssessmentOrdersAssessmentOrderIdResultRequestBodyRemoteFields
        extend T::Sig
        include Crystalline::MetadataFields


        field :smartrecruiters, Crystalline::Nilable.new(Models::Shared::PutAssessmentOrdersAssessmentOrderIdResultRequestBodySmartrecruiters), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('smartrecruiters') } }

        field :recruitee, Crystalline::Nilable.new(Models::Shared::PutAssessmentOrdersAssessmentOrderIdResultRequestBodyRecruitee), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('recruitee') } }
        # Fields specific to Workday's `Assess_Candidate` [operation](https://community.workday.com/sites/default/files/file-hosting/productionapi/Recruiting/v46.0/Assess_Candidate.html).
        field :workday, Crystalline::Nilable.new(Models::Shared::PutAssessmentOrdersAssessmentOrderIdResultRequestBodyWorkday), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('workday') } }

        sig { params(smartrecruiters: T.nilable(Models::Shared::PutAssessmentOrdersAssessmentOrderIdResultRequestBodySmartrecruiters), recruitee: T.nilable(Models::Shared::PutAssessmentOrdersAssessmentOrderIdResultRequestBodyRecruitee), workday: T.nilable(Models::Shared::PutAssessmentOrdersAssessmentOrderIdResultRequestBodyWorkday)).void }
        def initialize(smartrecruiters: nil, recruitee: nil, workday: nil)
          @smartrecruiters = smartrecruiters
          @recruitee = recruitee
          @workday = workday
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @smartrecruiters == other.smartrecruiters
          return false unless @recruitee == other.recruitee
          return false unless @workday == other.workday
          true
        end
      end
    end
  end
end
