# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared
      # Additional fields that we will pass through to specific ATS systems.
      class PutAssessmentOrdersAssessmentOrderIdResultRequestBodyRemoteFields
        extend T::Sig
        include Crystalline::MetadataFields


        field :smartrecruiters, Crystalline::Nilable.new(Models::Shared::PutAssessmentOrdersAssessmentOrderIdResultRequestBodySmartrecruiters), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('smartrecruiters') } }

        sig { params(smartrecruiters: T.nilable(Models::Shared::PutAssessmentOrdersAssessmentOrderIdResultRequestBodySmartrecruiters)).void }
        def initialize(smartrecruiters: nil)
          @smartrecruiters = smartrecruiters
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @smartrecruiters == other.smartrecruiters
          true
        end
      end
    end
  end
end
