# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared

      class PutAssessmentOrdersAssessmentOrderIdResultRequestBodyRecruitee
        extend T::Sig
        include Crystalline::MetadataFields

        # Value that we will pass through to Recruitee's `subtitle` field on the assessment report.
        field :subtitle, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('subtitle') } }

        sig { params(subtitle: T.nilable(::String)).void }
        def initialize(subtitle: nil)
          @subtitle = subtitle
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @subtitle == other.subtitle
          true
        end
      end
    end
  end
end
