# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared
      # PutAssessmentOrdersAssessmentOrderIdResultRequestBodyStatus - Status of the assessment.
      # 
      # **Please note the `status` can only be updated to a different value if its current value is `OPEN`.**
      class PutAssessmentOrdersAssessmentOrderIdResultRequestBodyStatus < T::Enum
        enums do
          COMPLETED = new('COMPLETED')
          CANCELLED = new('CANCELLED')
          OPEN = new('OPEN')
        end
      end
    end
  end
end
