# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared
      # ReadModelScopeConfigSetting - The setting of the datapoint in the scope config that you configured in the Kombo dashboard.
      class ReadModelScopeConfigSetting < T::Enum


        enums do
          ENABLED = new('ENABLED')
          DISABLED = new('DISABLED')
          OPTIONAL = new('OPTIONAL')
        end
      end
    end
  end
end
