# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared

      class RemoteWorkStatus
        include ::Crystalline::Enum
        enums do
          REMOTE = new('REMOTE')
          HYBRID = new('HYBRID')
          TEMPORARY = new('TEMPORARY')
          ON_SITE = new('ON_SITE')
        end
        open!
      end
    end
  end
end
