# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared

      class Schema2Object1
        extend T::Sig
        include Crystalline::MetadataFields


        field :label, ::String, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('label'), required: true } }

        field :required, Crystalline::Boolean.new, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('required'), required: true } }

        field :properties, Models::Shared::Schema1, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('properties'), required: true } }

        field :type, ::String, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('type'), required: true } }

        field :description, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('description') } }

        field :unified_key, Crystalline::Nilable.new(Models::Shared::Schema2UnifiedKey6), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('unified_key'), 'decoder': ::Kombo::Utils.enum_from_string(Models::Shared::Schema2UnifiedKey6, true) } }

        sig { params(label: ::String, required: T::Boolean, properties: Models::Shared::Schema1, type: ::String, description: T.nilable(::String), unified_key: T.nilable(Models::Shared::Schema2UnifiedKey6)).void }
        def initialize(label:, required:, properties:, type: 'object', description: nil, unified_key: nil)
          @label = label
          @required = required
          @properties = properties
          unless type == 'object'
            raise ArgumentError, 'Invalid value for type'
          end
          @type = 'object'
          @description = description
          @unified_key = unified_key
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @label == other.label
          return false unless @required == other.required
          return false unless @properties == other.properties
          return false unless @type == other.type
          return false unless @description == other.description
          return false unless @unified_key == other.unified_key
          true
        end
      end
    end
  end
end
