# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared

      class Stage
        extend T::Sig
        include Crystalline::MetadataFields

        # The globally unique ID of this object generated by Kombo. We recommend using this as a stable primary key for syncing.
        field :id, ::String, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('id'), required: true } }
        # The raw ID of the object in the remote system. We don't recommend using this as a primary key on your side as it might sometimes be compromised of multiple identifiers if a system doesn't provide a clear primary key.
        field :remote_id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('remote_id'), required: true } }
        # The application stage name. For example, "Initial Screening".
        field :name, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('name'), required: true } }
        # Whether the application stage is active in the ATS. Inactive stages (also e.g., archived or hidden) may still be referenced by existing applications but are typically not part of the current hiring workflow.
        field :status, Crystalline::Nilable.new(Models::Shared::StageStatus), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('status'), required: true, 'decoder': ::Kombo::Utils.enum_from_string(Models::Shared::StageStatus, false) } }
        # A key-value store of fields not covered by the schema. [Read more](/custom-fields)
        field :custom_fields, Crystalline::Nilable.new(Crystalline::Hash.new(Symbol, ::Object)), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('custom_fields'), required: true } }
        # Numeric index following the order of the stages if they are ordered in the underlying tool.
        field :index, Crystalline::Nilable.new(::Integer), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('index') } }

        sig { params(id: ::String, remote_id: T.nilable(::String), name: T.nilable(::String), status: T.nilable(Models::Shared::StageStatus), custom_fields: T.nilable(T::Hash[Symbol, ::Object]), index: T.nilable(::Integer)).void }
        def initialize(id:, remote_id: nil, name: nil, status: nil, custom_fields: nil, index: nil)
          @id = id
          @remote_id = remote_id
          @name = name
          @status = status
          @custom_fields = custom_fields
          @index = index
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @id == other.id
          return false unless @remote_id == other.remote_id
          return false unless @name == other.name
          return false unless @status == other.status
          return false unless @custom_fields == other.custom_fields
          return false unless @index == other.index
          true
        end
      end
    end
  end
end
