# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared

      class SummaryRatingSingleSelect
        extend T::Sig
        include Crystalline::MetadataFields


        field :type, ::String, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('type'), required: true } }
        # The options of the summary rating. Ordered from bad to good.
        field :ordered_options, Crystalline::Nilable.new(Crystalline::Array.new(::String)), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('ordered_options'), required: true } }
        # The text value of the summary rating.
        field :value, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('value'), required: true } }

        sig { params(type: ::String, ordered_options: T.nilable(T::Array[::String]), value: T.nilable(::String)).void }
        def initialize(type: 'SINGLE_SELECT', ordered_options: nil, value: nil)
          unless type == 'SINGLE_SELECT'
            raise ArgumentError, 'Invalid value for type'
          end
          @type = 'SINGLE_SELECT'
          @ordered_options = ordered_options
          @value = value
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @type == other.type
          return false unless @ordered_options == other.ordered_options
          return false unless @value == other.value
          true
        end
      end
    end
  end
end
