# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared

      class WorkLocation
        extend T::Sig
        include Crystalline::MetadataFields

        # The globally unique ID of this object generated by Kombo. We recommend using this as a stable primary key for syncing.
        field :id, ::String, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('id'), required: true } }
        # The timestamp when this specific record was last modified. This field only updates when properties directly on this record change, NOT when related or nested models change. For filtering that considers nested data changes, use the `updated_after` parameter which will return records when either the record itself OR its related models have been updated.
        # https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString
        field :changed_at, ::DateTime, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('changed_at'), required: true, 'decoder': ::Kombo::Utils.datetime_from_iso_format(false) } }
        # The raw ID of the object in the remote system. We don't recommend using this as a primary key on your side as it might sometimes be compromised of multiple identifiers if a system doesn't provide a clear primary key.
        field :remote_id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('remote_id'), required: true } }
        # The work location’s name
        field :name, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('name'), required: true } }
        # The work location’s type. A freeform string.
        field :type, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('type'), required: true } }
        # The date and time the object was deleted in the remote system. Objects are automatically marked as deleted when Kombo can't retrieve them from the remote system anymore. Kombo will also anonymize entries 14 days after they disappear.
        # https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString
        field :remote_deleted_at, Crystalline::Nilable.new(::DateTime), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('remote_deleted_at'), required: true, 'decoder': ::Kombo::Utils.datetime_from_iso_format(false) } }
        # The work location’s address
        field :address, Crystalline::Nilable.new(Models::Shared::WorkLocationAddress), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('address') } }

        sig { params(id: ::String, changed_at: ::DateTime, remote_id: T.nilable(::String), name: T.nilable(::String), type: T.nilable(::String), remote_deleted_at: T.nilable(::DateTime), address: T.nilable(Models::Shared::WorkLocationAddress)).void }
        def initialize(id:, changed_at:, remote_id: nil, name: nil, type: nil, remote_deleted_at: nil, address: nil)
          @id = id
          @changed_at = changed_at
          @remote_id = remote_id
          @name = name
          @type = type
          @remote_deleted_at = remote_deleted_at
          @address = address
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @id == other.id
          return false unless @changed_at == other.changed_at
          return false unless @remote_id == other.remote_id
          return false unless @name == other.name
          return false unless @type == other.type
          return false unless @remote_deleted_at == other.remote_deleted_at
          return false unless @address == other.address
          true
        end
      end
    end
  end
end
