# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared

      class BankAccount
        extend T::Sig
        include Crystalline::MetadataFields

        # The internationally unique IBAN identifying this account. If we detect a valid IBAN from the account number and this field would otherwise be empty, we will automatically populate this field.
        field :iban, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('iban') } }
        # The internationally unique BIC/SWIFT code identifying the bank behind this account. If we detect a valid BIC from the domestic bank routing number and this field would otherwise be empty, we will automatically populate this field.
        field :bic, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('bic') } }
        # The bank-specific account number. Some companies use the account number field to put the IBAN here.
        field :account_number, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('account_number') } }
        # The name of the holder of this account.
        field :holder_name, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('holder_name') } }
        # The name of the bank behind this account.
        field :bank_name, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('bank_name') } }

        field :domestic_bank_routing, Crystalline::Nilable.new(Models::Shared::DomesticBankRouting), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('domestic_bank_routing') } }

        sig { params(iban: T.nilable(::String), bic: T.nilable(::String), account_number: T.nilable(::String), holder_name: T.nilable(::String), bank_name: T.nilable(::String), domestic_bank_routing: T.nilable(Models::Shared::DomesticBankRouting)).void }
        def initialize(iban: nil, bic: nil, account_number: nil, holder_name: nil, bank_name: nil, domestic_bank_routing: nil)
          @iban = iban
          @bic = bic
          @account_number = account_number
          @holder_name = holder_name
          @bank_name = bank_name
          @domestic_bank_routing = domestic_bank_routing
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @iban == other.iban
          return false unless @bic == other.bic
          return false unless @account_number == other.account_number
          return false unless @holder_name == other.holder_name
          return false unless @bank_name == other.bank_name
          return false unless @domestic_bank_routing == other.domestic_bank_routing
          true
        end
      end
    end
  end
end
