# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared

      class DeleteHrisAbsencesAbsenceIdPositiveResponseStatus < T::Enum


        enums do
          REQUESTED = new('REQUESTED')
          APPROVED = new('APPROVED')
          DECLINED = new('DECLINED')
          CANCELLED = new('CANCELLED')
          DELETED = new('DELETED')
        end
      end
    end
  end
end
