# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
      # Fields specific to ADP Workforce Now.
      class DeleteHrisAbsencesAbsenceIdRequestBodyAdpworkforcenow
        extend T::Sig
        include Crystalline::MetadataFields

        # [Required] The employment ID of the employee that the absence will be deleted from.
        field :employment_id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('employment_id') } }

        sig { params(employment_id: T.nilable(::String)).void }
        def initialize(employment_id: nil)
          @employment_id = employment_id
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @employment_id == other.employment_id
          true
        end
      end
    end
  end
end
