# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared

      class DeleteHrisAbsencesAbsenceIdRequestBody
        extend T::Sig
        include Crystalline::MetadataFields

        # Additional fields that we will pass through to specific HRIS systems.
        field :remote_fields, Crystalline::Nilable.new(Models::Shared::DeleteHrisAbsencesAbsenceIdRequestBodyRemoteFields), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('remote_fields') } }

        sig { params(remote_fields: T.nilable(Models::Shared::DeleteHrisAbsencesAbsenceIdRequestBodyRemoteFields)).void }
        def initialize(remote_fields: nil)
          @remote_fields = remote_fields
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @remote_fields == other.remote_fields
          true
        end
      end
    end
  end
end
