# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared

      class Ethnicity < T::Enum


        enums do
          WHITE = new('WHITE')
          ASIAN = new('ASIAN')
          HISPANIC_LATINO = new('HISPANIC_LATINO')
          HAWAIIAN = new('HAWAIIAN')
          NATIVE_AMERICAN = new('NATIVE_AMERICAN')
          BLACK_AFRICAN_AMERICAN = new('BLACK_AFRICAN_AMERICAN')
          MULTIPLE_ETHNICITIES = new('MULTIPLE_ETHNICITIES')
          DECLINE_TO_SPECIFY = new('DECLINE_TO_SPECIFY')
        end
      end
    end
  end
end
