# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared

      class GetAtsApplicationsPositiveResponseAnswer4
        extend T::Sig
        include Crystalline::MetadataFields


        field :checked, Crystalline::Nilable.new(Crystalline::Boolean.new), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('checked'), required: true } }

        sig { params(checked: T.nilable(T::Boolean)).void }
        def initialize(checked: nil)
          @checked = checked
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @checked == other.checked
          true
        end
      end
    end
  end
end
