# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared

      class GetAtsJobsPositiveResponseStatus < T::Enum


        enums do
          OPEN = new('OPEN')
          CLOSED = new('CLOSED')
          DRAFT = new('DRAFT')
          ARCHIVED = new('ARCHIVED')
        end
      end
    end
  end
end
