# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared

      class GetAtsApplicationsPositiveResponseSocialMedia
        extend T::Sig
        include Crystalline::MetadataFields


        field :link, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('link') } }

        field :type, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('type') } }

        field :username, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('username') } }

        sig { params(link: T.nilable(::String), type: T.nilable(::String), username: T.nilable(::String)).void }
        def initialize(link: nil, type: nil, username: nil)
          @link = link
          @type = type
          @username = username
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @link == other.link
          return false unless @type == other.type
          return false unless @username == other.username
          true
        end
      end
    end
  end
end
