# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared
      # Information about the job posting.
      class GetAssessmentOrdersOpenPositiveResponseJob
        extend T::Sig
        include Crystalline::MetadataFields

        # The hiring team allows you to provision users into your system who can access the job and its applications.
        field :hiring_team, Crystalline::Array.new(Models::Shared::GetAssessmentOrdersOpenPositiveResponseHiringTeam), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('hiring_team'), required: true } }
        # The job's identifier in the integrated system.
        field :remote_id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('remote_id') } }
        # The job title.
        field :name, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('name') } }
        # The job location information.
        field :location, Crystalline::Nilable.new(Models::Shared::GetAssessmentOrdersOpenPositiveResponseLocation), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('location') } }

        sig { params(hiring_team: T::Array[Models::Shared::GetAssessmentOrdersOpenPositiveResponseHiringTeam], remote_id: T.nilable(::String), name: T.nilable(::String), location: T.nilable(Models::Shared::GetAssessmentOrdersOpenPositiveResponseLocation)).void }
        def initialize(hiring_team:, remote_id: nil, name: nil, location: nil)
          @hiring_team = hiring_team
          @remote_id = remote_id
          @name = name
          @location = location
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @hiring_team == other.hiring_team
          return false unless @remote_id == other.remote_id
          return false unless @name == other.name
          return false unless @location == other.location
          true
        end
      end
    end
  end
end
