# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared

      class GetAssessmentPackagesPositiveResponseData
        extend T::Sig
        include Crystalline::MetadataFields


        field :packages, Crystalline::Array.new(Models::Shared::GetAssessmentPackagesPositiveResponsePackage), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('packages'), required: true } }

        sig { params(packages: T::Array[Models::Shared::GetAssessmentPackagesPositiveResponsePackage]).void }
        def initialize(packages:)
          @packages = packages
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @packages == other.packages
          true
        end
      end
    end
  end
end
