# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
      # A member of the hiring team.
      class GetAssessmentOrdersOpenPositiveResponseHiringTeam
        extend T::Sig
        include Crystalline::MetadataFields

        # The team member's identifier in the integrated system.
        field :remote_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('remote_id'), required: true } }
        # Array of the roles of the user for this specific job. Currently only `RECRUITER` and `HIRING_MANAGER` are mapped into our unified schema.
        field :hiring_team_roles, Crystalline::Array.new(Models::Shared::GetAssessmentOrdersOpenPositiveResponseHiringTeamRole), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('hiring_team_roles'), required: true } }
        # The team member's email address.
        field :email, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('email'), required: true } }
        # The team member's first name.
        field :first_name, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('first_name'), required: true } }
        # The team member's last name.
        field :last_name, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('last_name'), required: true } }

        sig { params(remote_id: ::String, hiring_team_roles: T::Array[Models::Shared::GetAssessmentOrdersOpenPositiveResponseHiringTeamRole], email: T.nilable(::String), first_name: T.nilable(::String), last_name: T.nilable(::String)).void }
        def initialize(remote_id:, hiring_team_roles:, email: nil, first_name: nil, last_name: nil)
          @remote_id = remote_id
          @hiring_team_roles = hiring_team_roles
          @email = email
          @first_name = first_name
          @last_name = last_name
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @remote_id == other.remote_id
          return false unless @hiring_team_roles == other.hiring_team_roles
          return false unless @email == other.email
          return false unless @first_name == other.first_name
          return false unless @last_name == other.last_name
          true
        end
      end
    end
  end
end
