# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared

      class GetHrisEmployeesPositiveResponseEmploymentType < T::Enum


        enums do
          FULL_TIME = new('FULL_TIME')
          PART_TIME = new('PART_TIME')
          CONTRACT = new('CONTRACT')
          INTERNSHIP = new('INTERNSHIP')
          FREELANCE = new('FREELANCE')
          WORKING_STUDENT = new('WORKING_STUDENT')
          APPRENTICESHIP = new('APPRENTICESHIP')
          TRAINING = new('TRAINING')
        end
      end
    end
  end
end
