# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
      # GetIntegrationsIntegrationIdCustomFieldsPositiveResponseType - The type of the integration field. There is a type to avoid collisions between DEFAULT fields and CUSTOM fields with the same key.
      class GetIntegrationsIntegrationIdCustomFieldsPositiveResponseType < T::Enum


        enums do
          DEFAULT = new('DEFAULT')
          CUSTOM = new('CUSTOM')
        end
      end
    end
  end
end
