# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared

      class ImportedId
        extend T::Sig
        include Crystalline::MetadataFields


        field :erecruiter, Crystalline::Nilable.new(Crystalline::Union.new(Models::Shared::PostAtsImportTrackedApplicationPositiveResponseErecruiterApplicationAndJobRemoteIds, Models::Shared::PostAtsImportTrackedApplicationPositiveResponseErecruiterApplicationAndCandidateRemoteIds)), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('erecruiter') } }

        field :successfactors, Crystalline::Nilable.new(Models::Shared::PostAtsImportTrackedApplicationPositiveResponseSuccessfactorsApplicationRemoteID), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('successfactors') } }

        field :recruitee, Crystalline::Nilable.new(Models::Shared::PostAtsImportTrackedApplicationPositiveResponseRecruiteePlacementID), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('recruitee') } }

        field :greenhouse, Crystalline::Nilable.new(Models::Shared::PostAtsImportTrackedApplicationPositiveResponseGreenhouseApplicationID), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('greenhouse') } }

        field :onlyfy, Crystalline::Nilable.new(Models::Shared::PostAtsImportTrackedApplicationPositiveResponseOnlyfyApplicationID), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('onlyfy') } }

        field :smartrecruiters, Crystalline::Nilable.new(Models::Shared::PostAtsImportTrackedApplicationPositiveResponseSmartrecruitersCandidateAndJobRemoteIds), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('smartrecruiters') } }

        sig { params(erecruiter: T.nilable(T.any(Models::Shared::PostAtsImportTrackedApplicationPositiveResponseErecruiterApplicationAndJobRemoteIds, Models::Shared::PostAtsImportTrackedApplicationPositiveResponseErecruiterApplicationAndCandidateRemoteIds)), successfactors: T.nilable(Models::Shared::PostAtsImportTrackedApplicationPositiveResponseSuccessfactorsApplicationRemoteID), recruitee: T.nilable(Models::Shared::PostAtsImportTrackedApplicationPositiveResponseRecruiteePlacementID), greenhouse: T.nilable(Models::Shared::PostAtsImportTrackedApplicationPositiveResponseGreenhouseApplicationID), onlyfy: T.nilable(Models::Shared::PostAtsImportTrackedApplicationPositiveResponseOnlyfyApplicationID), smartrecruiters: T.nilable(Models::Shared::PostAtsImportTrackedApplicationPositiveResponseSmartrecruitersCandidateAndJobRemoteIds)).void }
        def initialize(erecruiter: nil, successfactors: nil, recruitee: nil, greenhouse: nil, onlyfy: nil, smartrecruiters: nil)
          @erecruiter = erecruiter
          @successfactors = successfactors
          @recruitee = recruitee
          @greenhouse = greenhouse
          @onlyfy = onlyfy
          @smartrecruiters = smartrecruiters
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @erecruiter == other.erecruiter
          return false unless @successfactors == other.successfactors
          return false unless @recruitee == other.recruitee
          return false unless @greenhouse == other.greenhouse
          return false unless @onlyfy == other.onlyfy
          return false unless @smartrecruiters == other.smartrecruiters
          true
        end
      end
    end
  end
end
