# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared
      # Information about the candidate taking the assessment.
      class InlineAssessmentOrderReceivedWebhookPayloadCandidate
        extend T::Sig
        include Crystalline::MetadataFields

        # The candidate's email address.
        field :email, ::String, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('email'), required: true } }
        # The candidate's identifier in the integrated system.
        field :remote_id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('remote_id') } }
        # The candidate's first name.
        field :first_name, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('first_name') } }
        # The candidate's last name.
        field :last_name, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('last_name') } }
        # The candidate's phone number.
        field :phone, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('phone') } }

        sig { params(email: ::String, remote_id: T.nilable(::String), first_name: T.nilable(::String), last_name: T.nilable(::String), phone: T.nilable(::String)).void }
        def initialize(email:, remote_id: nil, first_name: nil, last_name: nil, phone: nil)
          @email = email
          @remote_id = remote_id
          @first_name = first_name
          @last_name = last_name
          @phone = phone
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @email == other.email
          return false unless @remote_id == other.remote_id
          return false unless @first_name == other.first_name
          return false unless @last_name == other.last_name
          return false unless @phone == other.phone
          true
        end
      end
    end
  end
end
