# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared

      class Offer
        extend T::Sig
        include Crystalline::MetadataFields

        # The globally unique ID of this object generated by Kombo. We recommend using this as a stable primary key for syncing.
        field :id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('id'), required: true } }
        # The raw ID of the object in the remote system. We don't recommend using this as a primary key on your side as it might sometimes be compromised of multiple identifiers if a system doesn't provide a clear primary key.
        field :remote_id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('remote_id'), required: true } }
        # The offer’s current status. The usual flow of statuses is as follows:
        # `DRAFT` -> `APPROVED` -> `SENT` -> `ACCEPTED` or `DECLINED`.
        # 
        # Please note that not all systems will expose all statuses. For example, most systems do not include the `APPROVED` status
        # 
        # - `ACCEPTED`: The offer was accepted by the candidate.
        # - `DECLINED`: The offer was declined by the candidate.
        # - `SENT`: The offer was sent to the candidate.
        # - `APPROVED`: The draft was approved.
        # - `DRAFT`: The offer is a draft and has not yet been sent to the candidate.
        # - `ABANDONED`: The offer has expired or is no longer valid and should not be considered.
        # 
        field :status, Crystalline::Nilable.new(Models::Shared::GetAtsApplicationsPositiveResponseStatus), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('status'), required: true, 'decoder': Utils.enum_from_string(Models::Shared::GetAtsApplicationsPositiveResponseStatus, false) } }

        sig { params(id: ::String, remote_id: T.nilable(::String), status: T.nilable(Models::Shared::GetAtsApplicationsPositiveResponseStatus)).void }
        def initialize(id:, remote_id: nil, status: nil)
          @id = id
          @remote_id = remote_id
          @status = status
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @id == other.id
          return false unless @remote_id == other.remote_id
          return false unless @status == other.status
          true
        end
      end
    end
  end
end
