# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared

      class PatchIntegrationsIntegrationIdIntegrationFieldsIntegrationFieldIdRequestBody
        extend T::Sig
        include Crystalline::MetadataFields


        field :enable_passthrough, Crystalline::Nilable.new(Crystalline::Boolean.new), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('enable_passthrough'), required: true } }

        sig { params(enable_passthrough: T.nilable(T::Boolean)).void }
        def initialize(enable_passthrough: nil)
          @enable_passthrough = enable_passthrough
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @enable_passthrough == other.enable_passthrough
          true
        end
      end
    end
  end
end
