# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared
      # Fields specific to TalentSoft.
      class PostAtsCandidatesRequestBodyTalentsoft
        extend T::Sig
        include Crystalline::MetadataFields

        # Fields that we will pass through to TalentSoft's `applicant` object.
        field :applicant, Crystalline::Nilable.new(Crystalline::Hash.new(Symbol, ::Object)), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('applicant') } }
        # Fields that we will pass through to TalentSoft's `application` object.
        field :application, Crystalline::Nilable.new(Crystalline::Hash.new(Symbol, ::Object)), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('application') } }

        sig { params(applicant: T.nilable(T::Hash[Symbol, ::Object]), application: T.nilable(T::Hash[Symbol, ::Object])).void }
        def initialize(applicant: nil, application: nil)
          @applicant = applicant
          @application = application
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @applicant == other.applicant
          return false unless @application == other.application
          true
        end
      end
    end
  end
end
