# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
      # PostIntegrationsIntegrationIdRelinkRequestBodyLanguage - Language of the connection flow UI.
      class PostIntegrationsIntegrationIdRelinkRequestBodyLanguage < T::Enum


        enums do
          EN = new('en')
          DE = new('de')
          FR = new('fr')
          IT = new('it')
          ES = new('es')
        end
      end
    end
  end
end
