# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
      # Oracle specific remote fields for the attachment.
      class PostAtsApplicationsApplicationIdAttachmentsRequestBodyOracle
        extend T::Sig
        include Crystalline::MetadataFields

        # Allows you to override the document category for the attachment.
        field :override_document_category, Crystalline::Nilable.new(Models::Shared::PostAtsApplicationsApplicationIdAttachmentsRequestBodyOverrideDocumentCategory), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('override_document_category'), 'decoder': Utils.enum_from_string(Models::Shared::PostAtsApplicationsApplicationIdAttachmentsRequestBodyOverrideDocumentCategory, true) } }
        # If true, the attachment will be posted to all current applications for the candidate.
        field :multi_post_to_all_current_applications, Crystalline::Nilable.new(Crystalline::Boolean.new), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('multi_post_to_all_current_applications') } }

        sig { params(override_document_category: T.nilable(Models::Shared::PostAtsApplicationsApplicationIdAttachmentsRequestBodyOverrideDocumentCategory), multi_post_to_all_current_applications: T.nilable(T::Boolean)).void }
        def initialize(override_document_category: nil, multi_post_to_all_current_applications: nil)
          @override_document_category = override_document_category
          @multi_post_to_all_current_applications = multi_post_to_all_current_applications
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @override_document_category == other.override_document_category
          return false unless @multi_post_to_all_current_applications == other.multi_post_to_all_current_applications
          true
        end
      end
    end
  end
end
