# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared

      class PostAtsImportTrackedApplicationPositiveResponseErecruiterApplicationAndJobRemoteIds
        extend T::Sig
        include Crystalline::MetadataFields

        # Uses the `Api/Applications/ByJob/{jobId}` endpoint to retrieve the relevant application based on the job ID.
        field :id_type, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('id_type'), required: true } }

        field :application_remote_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('application_remote_id'), required: true } }

        field :job_remote_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('job_remote_id'), required: true } }

        sig { params(id_type: ::String, application_remote_id: ::String, job_remote_id: ::String).void }
        def initialize(id_type:, application_remote_id:, job_remote_id:)
          unless id_type == 'application_and_job_remote_ids'
            raise ArgumentError, 'Invalid value for id_type'
          end
          @id_type = 'application_and_job_remote_ids'
          @application_remote_id = application_remote_id
          @job_remote_id = job_remote_id
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @id_type == other.id_type
          return false unless @application_remote_id == other.application_remote_id
          return false unless @job_remote_id == other.job_remote_id
          true
        end
      end
    end
  end
end
