# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared

      class PostAtsCandidatesRequestBodyScreeningQuestionAnswer
        extend T::Sig
        include Crystalline::MetadataFields

        # ID of the question returned by the Kombo API. We'll report a warning in the logs if the question can't be found on the job.
        field :question_id, ::String, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('question_id'), required: true } }
        # Answer to a question. This will be validated based on the question format and throw an error if the answer is invalid. Here is a description of each question type and the required answer format:
        # 
        # `TEXT` - Simply provide a "string" answer.
        # 
        # `SINGLE_SELECT` - Provide the ID of the answer as a string.
        # 
        # `MULTI_SELECT` - Provide a string array containing the question IDs of the selected options.
        # 
        # `BOOLEAN` - Either `true` or `false`.
        # 
        # `NUMBER` - A number.
        # 
        # `DATE` - Provide the answer as an ISO 8601 date string.
        # 
        # `FILE` - Please select Option 6 in the dropdown above to see the required format.
        field :answer, Crystalline::Union.new(::String, Crystalline::Boolean.new, ::Float, Crystalline::Array.new(::String), ::DateTime, Models::Shared::PostAtsCandidatesRequestBodyAnswer), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('answer'), required: true } }

        sig { params(question_id: ::String, answer: T.any(::String, T::Boolean, ::Float, T::Array[::String], ::DateTime, Models::Shared::PostAtsCandidatesRequestBodyAnswer)).void }
        def initialize(question_id:, answer:)
          @question_id = question_id
          @answer = answer
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @question_id == other.question_id
          return false unless @answer == other.answer
          true
        end
      end
    end
  end
end
