# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
      # Fields specific to Abacus Umantis.
      class PostAtsCandidatesRequestBodyUmantis
        extend T::Sig
        include Crystalline::MetadataFields

        # Fields that we will pass through to Abacus Umantis's "Create a person" endpoint's `attributes` when creating a candidate.
        field :person, Crystalline::Nilable.new(Crystalline::Hash.new(Symbol, ::Object)), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('person') } }

        sig { params(person: T.nilable(T::Hash[Symbol, ::Object])).void }
        def initialize(person: nil)
          @person = person
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @person == other.person
          true
        end
      end
    end
  end
end
