# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
      # Fields specific to Teamtailor.
      class PostAtsApplicationsApplicationIdRejectRequestBodyTeamtailor
        extend T::Sig
        include Crystalline::MetadataFields

        # The remote ID of the user that will be displayed in the UI as the one that performed the action. If not provided, the first admin user will be used.
        field :user_id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('user_id') } }

        sig { params(user_id: T.nilable(::String)).void }
        def initialize(user_id: nil)
          @user_id = user_id
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @user_id == other.user_id
          true
        end
      end
    end
  end
end
