# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared

      class PostAtsJobsJobIdApplicationsRequestBodyStep
        extend T::Sig
        include Crystalline::MetadataFields

        # The ID of the workflow step to assign to the candidate.
        field :id, ::Integer, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('id'), required: true } }

        sig { params(id: ::Integer).void }
        def initialize(id:)
          @id = id
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @id == other.id
          true
        end
      end
    end
  end
end
