# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared
      # Fields specific to Coveto REST.
      class PostAtsJobsJobIdApplicationsRequestBodyCovetorest
        extend T::Sig
        include Crystalline::MetadataFields

        # Additional candidate fields that will be passed to the Coveto candidate creation.
        field :candidate, Crystalline::Nilable.new(Models::Shared::PostAtsJobsJobIdApplicationsRequestBodyCovetorestCandidate), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('candidate') } }

        sig { params(candidate: T.nilable(Models::Shared::PostAtsJobsJobIdApplicationsRequestBodyCovetorestCandidate)).void }
        def initialize(candidate: nil)
          @candidate = candidate
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @candidate == other.candidate
          true
        end
      end
    end
  end
end
