# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared

      class PostAtsJobsJobIdApplicationsRequestBodyCountryCityReference
        extend T::Sig
        include Crystalline::MetadataFields


        field :wid, ::String, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('WID'), required: true } }

        sig { params(wid: ::String).void }
        def initialize(wid:)
          @wid = wid
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @wid == other.wid
          true
        end
      end
    end
  end
end
