# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared

      class PostHrisEmployeesEmployeeIdDocumentsRequestBody
        extend T::Sig
        include Crystalline::MetadataFields


        field :category_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('category_id'), required: true } }

        field :document, Models::Shared::Document, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('document'), required: true } }

        sig { params(category_id: ::String, document: Models::Shared::Document).void }
        def initialize(category_id:, document:)
          @category_id = category_id
          @document = document
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @category_id == other.category_id
          return false unless @document == other.document
          true
        end
      end
    end
  end
end
