# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared

      class PostAtsCandidatesRequestBodyContactData
        extend T::Sig
        include Crystalline::MetadataFields


        field :location_data, Crystalline::Nilable.new(Models::Shared::PostAtsCandidatesRequestBodyLocationData), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('Location_Data') } }

        sig { params(location_data: T.nilable(Models::Shared::PostAtsCandidatesRequestBodyLocationData)).void }
        def initialize(location_data: nil)
          @location_data = location_data
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @location_data == other.location_data
          true
        end
      end
    end
  end
end
