# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
      # Bullhorn specific remote fields for the note.
      class PostAtsApplicationsApplicationIdNotesRequestBodyBullhorn
        extend T::Sig
        include Crystalline::MetadataFields

        # The action (or type) associated with a Note. You can find all available note actions in a Bullhorn instance under System Settings > commentActionList. The default action is `Note`.
        field :action, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('action') } }

        sig { params(action: T.nilable(::String)).void }
        def initialize(action: nil)
          @action = action
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @action == other.action
          true
        end
      end
    end
  end
end
