# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
      # PostHrisAbsencesPositiveResponseUnit - The unit of time for this absence. Can be `HOURS` or `DAYS`.
      class PostHrisAbsencesPositiveResponseUnit < T::Enum


        enums do
          HOURS = new('HOURS')
          DAYS = new('DAYS')
        end
      end
    end
  end
end
