# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared
      # PostHrisAbsencesRequestBodyUnit - The time unit of the `amount` value. Specifying this also requires specifying `amount`.
      class PostHrisAbsencesRequestBodyUnit < T::Enum


        enums do
          HOURS = new('HOURS')
          DAYS = new('DAYS')
        end
      end
    end
  end
end
