# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared

      class PostAtsJobsJobIdApplicationsRequestBodyTeamtailor
        extend T::Sig
        include Crystalline::MetadataFields

        # Fields that we will pass through to Teamtailor's `Candidate` object.
        field :candidate, Crystalline::Nilable.new(Crystalline::Hash.new(Symbol, ::Object)), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('candidate') } }

        field :application, Crystalline::Nilable.new(Models::Shared::PostAtsJobsJobIdApplicationsRequestBodyTeamtailorApplication), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('application') } }

        sig { params(candidate: T.nilable(T::Hash[Symbol, ::Object]), application: T.nilable(Models::Shared::PostAtsJobsJobIdApplicationsRequestBodyTeamtailorApplication)).void }
        def initialize(candidate: nil, application: nil)
          @candidate = candidate
          @application = application
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @candidate == other.candidate
          return false unless @application == other.application
          true
        end
      end
    end
  end
end
