# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared

      class PostAtsJobsJobIdApplicationsRequestBodyWorkflow
        extend T::Sig
        include Crystalline::MetadataFields


        field :step, Crystalline::Nilable.new(Models::Shared::PostAtsJobsJobIdApplicationsRequestBodyStep), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('step') } }

        sig { params(step: T.nilable(Models::Shared::PostAtsJobsJobIdApplicationsRequestBodyStep)).void }
        def initialize(step: nil)
          @step = step
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @step == other.step
          true
        end
      end
    end
  end
end
