# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared

      class PostAtsImportTrackedApplicationRequestBodyRecruiteePlacementID
        extend T::Sig
        include Crystalline::MetadataFields

        # Uses the `/candidates` endpoint to retrieve all candidates, to find the relevant application based on the placement ID.
        field :id_type, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('id_type'), required: true } }

        field :placement_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('placement_id'), required: true } }

        sig { params(id_type: ::String, placement_id: ::String).void }
        def initialize(id_type:, placement_id:)
          unless id_type == 'placement_id'
            raise ArgumentError, 'Invalid value for id_type'
          end
          @id_type = 'placement_id'
          @placement_id = placement_id
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @id_type == other.id_type
          return false unless @placement_id == other.placement_id
          true
        end
      end
    end
  end
end
