# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared
      # Fields specific to SmartRecruiters.
      class PostAtsCandidatesRequestBodySmartrecruiters
        extend T::Sig
        include Crystalline::MetadataFields

        # **(⚠️ Deprecated - Use the `candidate` field instead.)** Fields that we will pass through to the SmartRecruiters's `Candidate` object when created with screening question answers. This API is used: https://developers.smartrecruiters.com/reference/createcandidate-1
        # 
        # @deprecated  true: This will be removed in a future release, please migrate away from it as soon as possible.
        field :candidate_with_questions, Crystalline::Nilable.new(Crystalline::Hash.new(Symbol, ::Object)), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('candidate_with_questions') } }
        # **(⚠️ Deprecated - Use the `candidate` field instead.)** Fields that we will pass through to the SmartRecruiters's `Candidate` object when created with screening question answers. This API is used: https://developers.smartrecruiters.com/reference/candidatesaddtojob-1
        # 
        # @deprecated  true: This will be removed in a future release, please migrate away from it as soon as possible.
        field :candidate_without_questions, Crystalline::Nilable.new(Crystalline::Hash.new(Symbol, ::Object)), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('candidate_without_questions') } }
        # Fields that we will pass through to the SmartRecruiters's `Candidate` object. This API is used: https://developers.smartrecruiters.com/reference/createcandidate-1
        field :candidate, Crystalline::Nilable.new(Crystalline::Hash.new(Symbol, ::Object)), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('candidate') } }

        sig { params(candidate_with_questions: T.nilable(T::Hash[Symbol, ::Object]), candidate_without_questions: T.nilable(T::Hash[Symbol, ::Object]), candidate: T.nilable(T::Hash[Symbol, ::Object])).void }
        def initialize(candidate_with_questions: nil, candidate_without_questions: nil, candidate: nil)
          @candidate_with_questions = candidate_with_questions
          @candidate_without_questions = candidate_without_questions
          @candidate = candidate
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @candidate_with_questions == other.candidate_with_questions
          return false unless @candidate_without_questions == other.candidate_without_questions
          return false unless @candidate == other.candidate
          true
        end
      end
    end
  end
end
