# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared
      # Fields specific to Greenhouse.
      class PostAtsCandidatesCandidateIdAttachmentsRequestBodyGreenhouse
        extend T::Sig
        include Crystalline::MetadataFields

        # Headers we will pass with `POST` requests to Greenhouse.
        field :post_headers, Crystalline::Nilable.new(Models::Shared::PostAtsCandidatesCandidateIdAttachmentsRequestBodyPostHeaders), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('post_headers') } }

        sig { params(post_headers: T.nilable(Models::Shared::PostAtsCandidatesCandidateIdAttachmentsRequestBodyPostHeaders)).void }
        def initialize(post_headers: nil)
          @post_headers = post_headers
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @post_headers == other.post_headers
          true
        end
      end
    end
  end
end
