# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared

      class PostAtsCandidatesRequestBodyAdditionalEmailAddressType < T::Enum


        enums do
          PERSONAL = new('PERSONAL')
          WORK = new('WORK')
          OTHER = new('OTHER')
        end
      end
    end
  end
end
