# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared

      class PostAtsJobsJobIdApplicationsRequestBodyTeamtailorApplication
        extend T::Sig
        include Crystalline::MetadataFields

        # Fields that we will pass through to Teamtailor's attributes section `Job application` object.
        field :attributes, Crystalline::Nilable.new(Crystalline::Hash.new(Symbol, ::Object)), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('attributes') } }

        sig { params(attributes: T.nilable(T::Hash[Symbol, ::Object])).void }
        def initialize(attributes: nil)
          @attributes = attributes
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @attributes == other.attributes
          true
        end
      end
    end
  end
end
