# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared

      class PostAtsJobsJobIdApplicationsPositiveResponseAnswer6
        extend T::Sig
        include Crystalline::MetadataFields


        field :date, Crystalline::Nilable.new(::DateTime), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('date'), required: true, 'decoder': Utils.datetime_from_iso_format(false) } }

        sig { params(date: T.nilable(::DateTime)).void }
        def initialize(date: nil)
          @date = date
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @date == other.date
          true
        end
      end
    end
  end
end
