# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared

      class PostAtsJobsJobIdApplicationsPositiveResponseQuestionSingleSelect
        extend T::Sig
        include Crystalline::MetadataFields


        field :title, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('title'), required: true } }

        field :type, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('type'), required: true } }

        field :remote_id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('remote_id'), required: true } }

        sig { params(title: ::String, type: ::String, remote_id: T.nilable(::String)).void }
        def initialize(title:, type:, remote_id: nil)
          @title = title
          unless type == 'SINGLE_SELECT'
            raise ArgumentError, 'Invalid value for type'
          end
          @type = 'SINGLE_SELECT'
          @remote_id = remote_id
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @title == other.title
          return false unless @type == other.type
          return false unless @remote_id == other.remote_id
          true
        end
      end
    end
  end
end
