# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared

      class PostAtsCandidatesRequestBodyLanguageAbilityData
        extend T::Sig
        include Crystalline::MetadataFields


        field :language_proficiency_reference, Crystalline::Nilable.new(Models::Shared::PostAtsCandidatesRequestBodyLanguageProficiencyReference), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('Language_Proficiency_Reference') } }

        field :language_ability_type_reference, Crystalline::Nilable.new(Models::Shared::PostAtsCandidatesRequestBodyLanguageAbilityTypeReference), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('Language_Ability_Type_Reference') } }

        sig { params(language_proficiency_reference: T.nilable(Models::Shared::PostAtsCandidatesRequestBodyLanguageProficiencyReference), language_ability_type_reference: T.nilable(Models::Shared::PostAtsCandidatesRequestBodyLanguageAbilityTypeReference)).void }
        def initialize(language_proficiency_reference: nil, language_ability_type_reference: nil)
          @language_proficiency_reference = language_proficiency_reference
          @language_ability_type_reference = language_ability_type_reference
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @language_proficiency_reference == other.language_proficiency_reference
          return false unless @language_ability_type_reference == other.language_ability_type_reference
          true
        end
      end
    end
  end
end
