# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
      # PostConnectCreateLinkRequestBodyIntegrationCategory - Category of the integration you want your customer to create.
      class PostConnectCreateLinkRequestBodyIntegrationCategory < T::Enum


        enums do
          HRIS = new('HRIS')
          ATS = new('ATS')
          ASSESSMENT = new('ASSESSMENT')
          LMS = new('LMS')
        end
      end
    end
  end
end
