# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared

      class PropertiesSingleSelect
        extend T::Sig
        include Crystalline::MetadataFields


        field :label, ::String, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('label'), required: true } }

        field :required, Crystalline::Boolean.new, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('required'), required: true } }

        field :type, ::String, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('type'), required: true } }

        field :options, Crystalline::Union.new(Models::Shared::GetHrisEmployeesFormPositiveResponseOptionsInline1, Models::Shared::GetHrisEmployeesFormPositiveResponseOptionsReferenced1), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('options'), required: true } }

        field :description, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('description') } }

        field :unified_key, Crystalline::Nilable.new(Models::Shared::GetHrisEmployeesFormPositiveResponseUnifiedKey4), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('unified_key'), 'decoder': Utils.enum_from_string(Models::Shared::GetHrisEmployeesFormPositiveResponseUnifiedKey4, true) } }

        sig { params(label: ::String, required: T::Boolean, type: ::String, options: T.any(Models::Shared::GetHrisEmployeesFormPositiveResponseOptionsInline1, Models::Shared::GetHrisEmployeesFormPositiveResponseOptionsReferenced1), description: T.nilable(::String), unified_key: T.nilable(Models::Shared::GetHrisEmployeesFormPositiveResponseUnifiedKey4)).void }
        def initialize(label:, required:, type:, options:, description: nil, unified_key: nil)
          @label = label
          @required = required
          unless type == 'single_select'
            raise ArgumentError, 'Invalid value for type'
          end
          @type = 'single_select'
          @options = options
          @description = description
          @unified_key = unified_key
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @label == other.label
          return false unless @required == other.required
          return false unless @type == other.type
          return false unless @options == other.options
          return false unless @description == other.description
          return false unless @unified_key == other.unified_key
          true
        end
      end
    end
  end
end
