# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared

      class PropertiesMultiSelect
        extend T::Sig
        include Crystalline::MetadataFields


        field :label, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('label'), required: true } }

        field :required, Crystalline::Boolean.new, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('required'), required: true } }

        field :type, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('type'), required: true } }

        field :options, Crystalline::Union.new(Models::Shared::GetHrisEmployeesFormPositiveResponseOptionsInline2, Models::Shared::GetHrisEmployeesFormPositiveResponseOptionsReferenced2), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('options'), required: true } }

        field :description, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('description') } }

        field :unified_key, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('unified_key') } }

        field :min_items, Crystalline::Nilable.new(::Float), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('min_items') } }

        field :max_items, Crystalline::Nilable.new(::Float), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('max_items') } }

        sig { params(label: ::String, required: T::Boolean, type: ::String, options: T.any(Models::Shared::GetHrisEmployeesFormPositiveResponseOptionsInline2, Models::Shared::GetHrisEmployeesFormPositiveResponseOptionsReferenced2), description: T.nilable(::String), unified_key: T.nilable(::String), min_items: T.nilable(::Float), max_items: T.nilable(::Float)).void }
        def initialize(label:, required:, type:, options:, description: nil, unified_key: nil, min_items: nil, max_items: nil)
          @label = label
          @required = required
          unless type == 'multi_select'
            raise ArgumentError, 'Invalid value for type'
          end
          @type = 'multi_select'
          @options = options
          @description = description
          @unified_key = unified_key
          @min_items = min_items
          @max_items = max_items
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @label == other.label
          return false unless @required == other.required
          return false unless @type == other.type
          return false unless @options == other.options
          return false unless @description == other.description
          return false unless @unified_key == other.unified_key
          return false unless @min_items == other.min_items
          return false unless @max_items == other.max_items
          true
        end
      end
    end
  end
end
