# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared

      class PutAssessmentOrdersAssessmentOrderIdResultRequestBody
        extend T::Sig
        include Crystalline::MetadataFields

        # Status of the assessment.
        # 
        # **Please note the `status` can only be updated to a different value if its current value is `OPEN`.**
        field :status, Models::Shared::PutAssessmentOrdersAssessmentOrderIdResultRequestBodyStatus, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('status'), required: true, 'decoder': Utils.enum_from_string(Models::Shared::PutAssessmentOrdersAssessmentOrderIdResultRequestBodyStatus, false) } }

        field :result_url, ::String, { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('result_url'), required: true } }
        # YYYY-MM-DDTHH:mm:ss.sssZ
        # 
        # **Please make sure this value is provided when the `status` is of the type `COMPLETED` or `CANCELLED`.**
        # https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString
        field :completed_at, Crystalline::Nilable.new(::DateTime), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('completed_at'), 'decoder': Utils.datetime_from_iso_format(true) } }

        field :score, Crystalline::Nilable.new(::Float), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('score') } }

        field :max_score, Crystalline::Nilable.new(::Float), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('max_score') } }
        # An array of additional attributes that you would like to submit as a part of the assessment result.
        # 
        # - If an ATS only supports writing text attributes, we will transform non `TEXT` attributes into formatted plain text values.
        field :attributes, Crystalline::Nilable.new(Crystalline::Array.new(Crystalline::Union.new(Models::Shared::AttributeText, Models::Shared::AttributeSubResult))), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('attributes') } }
        # An array of attachments containing the assessment result.
        field :attachments, Crystalline::Nilable.new(Crystalline::Array.new(Models::Shared::PutAssessmentOrdersAssessmentOrderIdResultRequestBodyAttachment)), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('attachments') } }
        # Additional fields that we will pass through to specific ATS systems.
        field :remote_fields, Crystalline::Nilable.new(Models::Shared::PutAssessmentOrdersAssessmentOrderIdResultRequestBodyRemoteFields), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('remote_fields') } }

        sig { params(status: Models::Shared::PutAssessmentOrdersAssessmentOrderIdResultRequestBodyStatus, result_url: ::String, completed_at: T.nilable(::DateTime), score: T.nilable(::Float), max_score: T.nilable(::Float), attributes: T.nilable(T::Array[T.any(Models::Shared::AttributeText, Models::Shared::AttributeSubResult)]), attachments: T.nilable(T::Array[Models::Shared::PutAssessmentOrdersAssessmentOrderIdResultRequestBodyAttachment]), remote_fields: T.nilable(Models::Shared::PutAssessmentOrdersAssessmentOrderIdResultRequestBodyRemoteFields)).void }
        def initialize(status:, result_url:, completed_at: nil, score: nil, max_score: nil, attributes: nil, attachments: nil, remote_fields: nil)
          @status = status
          @result_url = result_url
          @completed_at = completed_at
          @score = score
          @max_score = max_score
          @attributes = attributes
          @attachments = attachments
          @remote_fields = remote_fields
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @status == other.status
          return false unless @result_url == other.result_url
          return false unless @completed_at == other.completed_at
          return false unless @score == other.score
          return false unless @max_score == other.max_score
          return false unless @attributes == other.attributes
          return false unless @attachments == other.attachments
          return false unless @remote_fields == other.remote_fields
          true
        end
      end
    end
  end
end
