# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Shared
      # Additional fields that we will pass through to specific ATS systems.
      class PutAtsApplicationsApplicationIdStageRequestBodyRemoteFields
        extend T::Sig
        include Crystalline::MetadataFields

        # Fields specific to Greenhouse.
        field :greenhouse, Crystalline::Nilable.new(Models::Shared::PutAtsApplicationsApplicationIdStageRequestBodyGreenhouse), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('greenhouse') } }
        # Workable specific remote fields for ATS actions.
        field :workable, Crystalline::Nilable.new(Models::Shared::PutAtsApplicationsApplicationIdStageRequestBodyWorkable), { 'format_json': { 'letter_case': ::Kombo::Utils.field_name('workable') } }

        sig { params(greenhouse: T.nilable(Models::Shared::PutAtsApplicationsApplicationIdStageRequestBodyGreenhouse), workable: T.nilable(Models::Shared::PutAtsApplicationsApplicationIdStageRequestBodyWorkable)).void }
        def initialize(greenhouse: nil, workable: nil)
          @greenhouse = greenhouse
          @workable = workable
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @greenhouse == other.greenhouse
          return false unless @workable == other.workable
          true
        end
      end
    end
  end
end
