# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared

      class Schema2FileRestrictions
        extend T::Sig
        include Crystalline::MetadataFields


        field :accepted_mime_types, Crystalline::Array.new(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('accepted_mime_types'), required: true } }

        field :max_file_size, Crystalline::Nilable.new(::Float), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('max_file_size') } }

        sig { params(accepted_mime_types: T::Array[::String], max_file_size: T.nilable(::Float)).void }
        def initialize(accepted_mime_types:, max_file_size: nil)
          @accepted_mime_types = accepted_mime_types
          @max_file_size = max_file_size
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @accepted_mime_types == other.accepted_mime_types
          return false unless @max_file_size == other.max_file_size
          true
        end
      end
    end
  end
end
