# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared

      class Schema2OptionsReferenced1
        extend T::Sig
        include Crystalline::MetadataFields


        field :type, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('type'), required: true } }

        field :link, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('link'), required: true } }

        sig { params(type: ::String, link: ::String).void }
        def initialize(type:, link:)
          unless type == 'referenced'
            raise ArgumentError, 'Invalid value for type'
          end
          @type = 'referenced'
          @link = link
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @type == other.type
          return false unless @link == other.link
          true
        end
      end
    end
  end
end
