# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared

      class Schema2File
        extend T::Sig
        include Crystalline::MetadataFields


        field :label, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('label'), required: true } }

        field :required, Crystalline::Boolean.new, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('required'), required: true } }

        field :type, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('type'), required: true } }

        field :file_restrictions, Models::Shared::Schema2FileRestrictions, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('file_restrictions'), required: true } }

        field :description, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('description') } }

        field :unified_key, Crystalline::Nilable.new(Models::Shared::Schema2UnifiedKey8), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('unified_key'), 'decoder': Utils.enum_from_string(Models::Shared::Schema2UnifiedKey8, true) } }

        sig { params(label: ::String, required: T::Boolean, type: ::String, file_restrictions: Models::Shared::Schema2FileRestrictions, description: T.nilable(::String), unified_key: T.nilable(Models::Shared::Schema2UnifiedKey8)).void }
        def initialize(label:, required:, type:, file_restrictions:, description: nil, unified_key: nil)
          @label = label
          @required = required
          unless type == 'file'
            raise ArgumentError, 'Invalid value for type'
          end
          @type = 'file'
          @file_restrictions = file_restrictions
          @description = description
          @unified_key = unified_key
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @label == other.label
          return false unless @required == other.required
          return false unless @type == other.type
          return false unless @file_restrictions == other.file_restrictions
          return false unless @description == other.description
          return false unless @unified_key == other.unified_key
          true
        end
      end
    end
  end
end
