# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared

      class ScreeningQuestion
        extend T::Sig
        include Crystalline::MetadataFields

        # The globally unique ID of this object generated by Kombo. We recommend using this as a stable primary key for syncing.
        field :id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('id'), required: true } }
        # The raw ID of the object in the remote system. We don't recommend using this as a primary key on your side as it might sometimes be compromised of multiple identifiers if a system doesn't provide a clear primary key.
        field :remote_id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('remote_id'), required: true } }

        field :title, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('title'), required: true } }
        # Additional instructions or context. Typically a short sentence, but sometimes a long detailed description (e.g., for EEO questions). May include HTML for extra formatting.
        field :description, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('description'), required: true } }
        # The category of the screening question (default `null`). "EEO" questions are related to Equal Employment Opportunity (e.g. "What is your veteran status?"), while "DEMOGRAPHIC" questions are for other diversity and demographic data collection.
        field :category, Crystalline::Nilable.new(Models::Shared::GetAtsJobsPositiveResponseCategory), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('category'), required: true, 'decoder': Utils.enum_from_string(Models::Shared::GetAtsJobsPositiveResponseCategory, false) } }

        field :required, Crystalline::Nilable.new(Crystalline::Boolean.new), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('required'), required: true } }

        field :format, Crystalline::Nilable.new(Crystalline::Union.new(Models::Shared::FormatText, Models::Shared::FormatNumber, Models::Shared::FormatFile, Models::Shared::FormatSingleSelect, Models::Shared::FormatBoolean, Models::Shared::FormatDate, Models::Shared::FormatMultiSelect, Models::Shared::FormatInformation, Models::Shared::FormatUnknown)), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('format') } }

        field :index, Crystalline::Nilable.new(::Integer), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('index') } }
        # The Kombo ID of another screening question. Only display this question if the specified "precondition question" is answered with one of the values in `precondition_options`.
        field :precondition_question_id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('precondition_question_id') } }
        # Where the screening question specified by `precondition_question_id` is of type `MULTI_SELECT` or `SINGLE_SELECT`, this is an array of Kombo IDs describing the valid options. If the question is of type `BOOLEAN`, this is an array containing either `true` or `false`.
        field :precondition_options, Crystalline::Nilable.new(Crystalline::Array.new(::String)), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('precondition_options') } }

        sig { params(id: ::String, remote_id: T.nilable(::String), title: T.nilable(::String), description: T.nilable(::String), category: T.nilable(Models::Shared::GetAtsJobsPositiveResponseCategory), required: T.nilable(T::Boolean), format: T.nilable(T.any(Models::Shared::FormatText, Models::Shared::FormatNumber, Models::Shared::FormatFile, Models::Shared::FormatSingleSelect, Models::Shared::FormatBoolean, Models::Shared::FormatDate, Models::Shared::FormatMultiSelect, Models::Shared::FormatInformation, Models::Shared::FormatUnknown)), index: T.nilable(::Integer), precondition_question_id: T.nilable(::String), precondition_options: T.nilable(T::Array[::String])).void }
        def initialize(id:, remote_id: nil, title: nil, description: nil, category: nil, required: nil, format: nil, index: nil, precondition_question_id: nil, precondition_options: nil)
          @id = id
          @remote_id = remote_id
          @title = title
          @description = description
          @category = category
          @required = required
          @format = format
          @index = index
          @precondition_question_id = precondition_question_id
          @precondition_options = precondition_options
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @id == other.id
          return false unless @remote_id == other.remote_id
          return false unless @title == other.title
          return false unless @description == other.description
          return false unless @category == other.category
          return false unless @required == other.required
          return false unless @format == other.format
          return false unless @index == other.index
          return false unless @precondition_question_id == other.precondition_question_id
          return false unless @precondition_options == other.precondition_options
          true
        end
      end
    end
  end
end
