# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared

      class TimeOffBalance
        extend T::Sig
        include Crystalline::MetadataFields

        # The globally unique ID of this object generated by Kombo. We recommend using this as a stable primary key for syncing.
        field :id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('id'), required: true } }
        # The Kombo ID of the employee to which the balance belongs to. The ID can be used to retrieve the employee from the `get employees` endpoint.
        field :employee_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('employee_id'), required: true } }

        field :type_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('type_id'), required: true } }
        # The timestamp when this specific record was last modified. This field only updates when properties directly on this record change, NOT when related or nested models change. For filtering that considers nested data changes, use the `updated_after` parameter which will return records when either the record itself OR its related models have been updated.
        # https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString
        field :changed_at, ::DateTime, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('changed_at'), required: true, 'decoder': Utils.datetime_from_iso_format(false) } }
        # The raw ID of the object in the remote system. We don't recommend using this as a primary key on your side as it might sometimes be compromised of multiple identifiers if a system doesn't provide a clear primary key.
        field :remote_id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('remote_id'), required: true } }
        # The amount of time available to the employee.
        field :balance, Crystalline::Nilable.new(::Float), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('balance'), required: true } }
        # The time-unit of the balance.
        field :balance_unit, Crystalline::Nilable.new(Models::Shared::GetHrisEmployeesPositiveResponseBalanceUnit), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('balance_unit'), required: true, 'decoder': Utils.enum_from_string(Models::Shared::GetHrisEmployeesPositiveResponseBalanceUnit, false) } }
        # The date and time the object was deleted in the remote system. Objects are automatically marked as deleted when Kombo can't retrieve them from the remote system anymore. Kombo will also anonymize entries 14 days after they disappear.
        # https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString
        field :remote_deleted_at, Crystalline::Nilable.new(::DateTime), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('remote_deleted_at'), required: true, 'decoder': Utils.datetime_from_iso_format(false) } }
        # The amount of time used by the employee.
        field :used, Crystalline::Nilable.new(::Float), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('used'), required: true } }
        # The time-unit of the used time.
        field :used_unit, Crystalline::Nilable.new(Models::Shared::GetHrisEmployeesPositiveResponseUsedUnit), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('used_unit'), required: true, 'decoder': Utils.enum_from_string(Models::Shared::GetHrisEmployeesPositiveResponseUsedUnit, false) } }

        sig { params(id: ::String, employee_id: ::String, type_id: ::String, changed_at: ::DateTime, remote_id: T.nilable(::String), balance: T.nilable(::Float), balance_unit: T.nilable(Models::Shared::GetHrisEmployeesPositiveResponseBalanceUnit), remote_deleted_at: T.nilable(::DateTime), used: T.nilable(::Float), used_unit: T.nilable(Models::Shared::GetHrisEmployeesPositiveResponseUsedUnit)).void }
        def initialize(id:, employee_id:, type_id:, changed_at:, remote_id: nil, balance: nil, balance_unit: nil, remote_deleted_at: nil, used: nil, used_unit: nil)
          @id = id
          @employee_id = employee_id
          @type_id = type_id
          @changed_at = changed_at
          @remote_id = remote_id
          @balance = balance
          @balance_unit = balance_unit
          @remote_deleted_at = remote_deleted_at
          @used = used
          @used_unit = used_unit
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @id == other.id
          return false unless @employee_id == other.employee_id
          return false unless @type_id == other.type_id
          return false unless @changed_at == other.changed_at
          return false unless @remote_id == other.remote_id
          return false unless @balance == other.balance
          return false unless @balance_unit == other.balance_unit
          return false unless @remote_deleted_at == other.remote_deleted_at
          return false unless @used == other.used
          return false unless @used_unit == other.used_unit
          true
        end
      end
    end
  end
end
