# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared

      class Visibility < T::Enum


        enums do
          PUBLIC = new('PUBLIC')
          INTERNAL = new('INTERNAL')
          UNLISTED = new('UNLISTED')
          CONFIDENTIAL = new('CONFIDENTIAL')
        end
      end
    end
  end
end
