# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Components

      class Assets
        extend T::Sig
        include Crystalline::MetadataFields


        field :logo_url, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('logo_url'), required: true } }

        field :icon_url, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('icon_url'), required: true } }

        field :icon_black_url, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('icon_black_url'), required: true } }

        sig { params(logo_url: ::String, icon_url: ::String, icon_black_url: ::String).void }
        def initialize(logo_url:, icon_url:, icon_black_url:)
          @logo_url = logo_url
          @icon_url = icon_url
          @icon_black_url = icon_black_url
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @logo_url == other.logo_url
          return false unless @icon_url == other.icon_url
          return false unless @icon_black_url == other.icon_black_url
          true
        end
      end
    end
  end
end
