# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Components

      class DataChangedWebhookPayloadData
        extend T::Sig
        include Crystalline::MetadataFields

        # The unique identifier of the integration.
        field :integration_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('integration_id'), required: true } }
        # The name of the integrated tool (e.g., "personio", "greenhouse").
        field :integration_tool, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('integration_tool'), required: true } }
        # The category of the integration (HRIS, ATS, ASSESSMENT, or LMS).
        field :integration_category, Models::Components::DataChangedWebhookPayloadIntegrationCategory, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('integration_category'), required: true, 'decoder': Utils.enum_from_string(Models::Components::DataChangedWebhookPayloadIntegrationCategory, false) } }
        # List of data models and connections for which one or more records were created, updated, or deleted.
        field :changed_models, Crystalline::Array.new(Models::Components::ChangedModel), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('changed_models'), required: true } }

        sig { params(integration_id: ::String, integration_tool: ::String, integration_category: Models::Components::DataChangedWebhookPayloadIntegrationCategory, changed_models: T::Array[Models::Components::ChangedModel]).void }
        def initialize(integration_id:, integration_tool:, integration_category:, changed_models:)
          @integration_id = integration_id
          @integration_tool = integration_tool
          @integration_category = integration_category
          @changed_models = changed_models
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @integration_id == other.integration_id
          return false unless @integration_tool == other.integration_tool
          return false unless @integration_category == other.integration_category
          return false unless @changed_models == other.changed_models
          true
        end
      end
    end
  end
end
