# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Components

      class DomesticBankRouting
        extend T::Sig
        include Crystalline::MetadataFields

        # Bank routing number (e.g. DE Bankleitzahl, GB Sort Code, US ABA routing number, AU BSB code). This field is not formatted and therefore might contain delimiters (eg. 01-23-45).
        field :number, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('number'), required: true } }
        # Enum of the routing type, prefixed with the iso-3166-1-alpha-2 banks origin country. If there is uncertainty about the type, it will be set to null.
        field :type, Crystalline::Nilable.new(Models::Components::DomesticBankRoutingType), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('type'), required: true, 'decoder': Utils.enum_from_string(Models::Components::DomesticBankRoutingType, false) } }

        sig { params(number: ::String, type: T.nilable(Models::Components::DomesticBankRoutingType)).void }
        def initialize(number:, type: nil)
          @number = number
          @type = type
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @number == other.number
          return false unless @type == other.type
          true
        end
      end
    end
  end
end
