# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Components

      class FormatText
        extend T::Sig
        include Crystalline::MetadataFields


        field :type, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('type'), required: true } }
        # If unavailable, we recommend displaying a single-line input.
        field :display_type, Crystalline::Nilable.new(Models::Components::DisplayType1), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('display_type'), 'decoder': Utils.enum_from_string(Models::Components::DisplayType1, true) } }

        field :max_length, Crystalline::Nilable.new(::Integer), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('max_length') } }

        sig { params(type: ::String, display_type: T.nilable(Models::Components::DisplayType1), max_length: T.nilable(::Integer)).void }
        def initialize(type:, display_type: nil, max_length: nil)
          unless type == 'TEXT'
            raise ArgumentError, 'Invalid value for type'
          end
          @type = 'TEXT'
          @display_type = display_type
          @max_length = max_length
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @type == other.type
          return false unless @display_type == other.display_type
          return false unless @max_length == other.max_length
          true
        end
      end
    end
  end
end
