# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Components

      class GetAssessmentPackagesPositiveResponsePackage
        extend T::Sig
        include Crystalline::MetadataFields


        field :id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('id'), required: true } }

        field :name, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('name'), required: true } }

        field :description, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('description'), required: true } }
        # YYYY-MM-DDTHH:mm:ss.sssZ
        # https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString
        field :updated_at, Crystalline::Nilable.new(::DateTime), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('updated_at'), required: true, 'decoder': Utils.datetime_from_iso_format(false) } }

        field :type, Crystalline::Nilable.new(Models::Components::GetAssessmentPackagesPositiveResponseType), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('type'), required: true, 'decoder': Utils.enum_from_string(Models::Components::GetAssessmentPackagesPositiveResponseType, false) } }

        sig { params(id: ::String, name: ::String, description: ::String, updated_at: T.nilable(::DateTime), type: T.nilable(Models::Components::GetAssessmentPackagesPositiveResponseType)).void }
        def initialize(id:, name:, description:, updated_at: nil, type: nil)
          @id = id
          @name = name
          @description = description
          @updated_at = updated_at
          @type = type
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @id == other.id
          return false unless @name == other.name
          return false unless @description == other.description
          return false unless @updated_at == other.updated_at
          return false unless @type == other.type
          true
        end
      end
    end
  end
end
