# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Components

      class GetAssessmentPackagesPositiveResponseType < T::Enum


        enums do
          BEHAVIORAL = new('BEHAVIORAL')
          VIDEO_INTERVIEW = new('VIDEO_INTERVIEW')
          SKILLS_TEST = new('SKILLS_TEST')
          BACKGROUND_CHECK = new('BACKGROUND_CHECK')
          REFERENCE_CHECK = new('REFERENCE_CHECK')
        end
      end
    end
  end
end
