# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Components

      class GetAssessmentOrdersOpenPositiveResponseHiringTeamRole < T::Enum


        enums do
          RECRUITER = new('RECRUITER')
          HIRING_MANAGER = new('HIRING_MANAGER')
        end
      end
    end
  end
end
