# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Components

      class GetAtsOffersPositiveResponseApplication
        extend T::Sig
        include Crystalline::MetadataFields


        field :candidate, Crystalline::Nilable.new(Models::Components::GetAtsOffersPositiveResponseCandidate), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('candidate'), required: true } }

        field :job, Crystalline::Nilable.new(Models::Components::GetAtsOffersPositiveResponseJob), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('job'), required: true } }

        sig { params(candidate: T.nilable(Models::Components::GetAtsOffersPositiveResponseCandidate), job: T.nilable(Models::Components::GetAtsOffersPositiveResponseJob)).void }
        def initialize(candidate: nil, job: nil)
          @candidate = candidate
          @job = job
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @candidate == other.candidate
          return false unless @job == other.job
          true
        end
      end
    end
  end
end
