# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Components

      class GetCheckApiKeyPositiveResponseData
        extend T::Sig
        include Crystalline::MetadataFields


        field :environment_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('environment_id'), required: true } }

        sig { params(environment_id: ::String).void }
        def initialize(environment_id:)
          @environment_id = environment_id
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @environment_id == other.environment_id
          true
        end
      end
    end
  end
end
