# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Components

      class GetHrisEmployeesFormPositiveResponseEntry2
        extend T::Sig
        include Crystalline::MetadataFields


        field :id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('id'), required: true } }

        field :label, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('label'), required: true } }

        field :remote_id, Crystalline::Union.new(::String, ::Float), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('remote_id'), required: true } }

        field :unified_value, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('unified_value') } }

        sig { params(id: ::String, label: ::String, remote_id: T.any(::String, ::Float), unified_value: T.nilable(::String)).void }
        def initialize(id:, label:, remote_id:, unified_value: nil)
          @id = id
          @label = label
          @remote_id = remote_id
          @unified_value = unified_value
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @id == other.id
          return false unless @label == other.label
          return false unless @remote_id == other.remote_id
          return false unless @unified_value == other.unified_value
          true
        end
      end
    end
  end
end
