# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Components
      # GetHrisAbsencesPositiveResponseTypeUnit - The time-unit of the absence.
      class GetHrisAbsencesPositiveResponseTypeUnit < T::Enum


        enums do
          HOURS = new('HOURS')
          DAYS = new('DAYS')
        end
      end
    end
  end
end
