# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Components

      class GetHrisEmployeesPositiveResponseGender < T::Enum


        enums do
          MALE = new('MALE')
          FEMALE = new('FEMALE')
          NON_BINARY = new('NON_BINARY')
          NOT_SPECIFIED = new('NOT_SPECIFIED')
        end
      end
    end
  end
end
