# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Components

      class GetIntegrationsIntegrationIdPositiveResponseEndUser
        extend T::Sig
        include Crystalline::MetadataFields


        field :organization_name, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('organization_name'), required: true } }

        field :creator_email, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('creator_email'), required: true } }
        # The ID you have passed initially to the connection flow to create this integration.
        field :origin_id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('origin_id'), required: true } }

        sig { params(organization_name: ::String, creator_email: T.nilable(::String), origin_id: T.nilable(::String)).void }
        def initialize(organization_name:, creator_email: nil, origin_id: nil)
          @organization_name = organization_name
          @creator_email = creator_email
          @origin_id = origin_id
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @organization_name == other.organization_name
          return false unless @creator_email == other.creator_email
          return false unless @origin_id == other.origin_id
          true
        end
      end
    end
  end
end
