# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Components

      class GetToolsCategoryPositiveResponseData
        extend T::Sig
        include Crystalline::MetadataFields


        field :tools, Crystalline::Array.new(Models::Components::GetToolsCategoryPositiveResponseTool), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('tools'), required: true } }

        sig { params(tools: T::Array[Models::Components::GetToolsCategoryPositiveResponseTool]).void }
        def initialize(tools:)
          @tools = tools
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @tools == other.tools
          true
        end
      end
    end
  end
end
