# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Components
      # Information about the job application.
      class InlineAssessmentOrderReceivedWebhookPayloadApplication
        extend T::Sig
        include Crystalline::MetadataFields

        # The application's identifier in the integrated system.
        field :remote_id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('remote_id') } }

        sig { params(remote_id: T.nilable(::String)).void }
        def initialize(remote_id: nil)
          @remote_id = remote_id
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @remote_id == other.remote_id
          true
        end
      end
    end
  end
end
