# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Components
      # IntegrationStateChangedWebhookPayloadType - Type of the webhook event
      class IntegrationStateChangedWebhookPayloadType < T::Enum


        enums do
          INTEGRATION_STATE_CHANGED = new('integration-state-changed')
        end
      end
    end
  end
end
