# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Components
      # IntegrationDeletedWebhookPayloadType - Type of the webhook event
      class IntegrationDeletedWebhookPayloadType < T::Enum


        enums do
          INTEGRATION_DELETED = new('integration-deleted')
        end
      end
    end
  end
end
