# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Components

      class KomboHrisErrorStatus < T::Enum


        enums do
          ERROR = new('error')
        end
      end
    end
  end
end
