# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Components
      # The data to submit as part of the request body if the request's `Content-Type` is `multipart/form-data`.
      class MultipartFormDatum
        extend T::Sig
        include Crystalline::MetadataFields

        # The key of the form data
        field :name, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('name'), required: true } }

        field :value, Crystalline::Union.new(::String, Models::Components::Value), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('value'), required: true } }

        sig { params(name: ::String, value: T.any(::String, Models::Components::Value)).void }
        def initialize(name:, value:)
          @name = name
          @value = value
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @name == other.name
          return false unless @value == other.value
          true
        end
      end
    end
  end
end
