# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Components
      # Additional fields that we will pass through to specific ATS systems.
      class PostAtsApplicationsApplicationIdAttachmentsRequestBodyRemoteFields
        extend T::Sig
        include Crystalline::MetadataFields

        # Oracle specific remote fields for the attachment.
        field :oracle, Crystalline::Nilable.new(Models::Components::PostAtsApplicationsApplicationIdAttachmentsRequestBodyOracle), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('oracle') } }
        # Fields specific to Greenhouse.
        field :greenhouse, Crystalline::Nilable.new(Models::Components::PostAtsApplicationsApplicationIdAttachmentsRequestBodyGreenhouse), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('greenhouse') } }
        # Workable specific remote fields for ATS actions.
        field :workable, Crystalline::Nilable.new(Models::Components::PostAtsApplicationsApplicationIdAttachmentsRequestBodyWorkable), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('workable') } }

        sig { params(oracle: T.nilable(Models::Components::PostAtsApplicationsApplicationIdAttachmentsRequestBodyOracle), greenhouse: T.nilable(Models::Components::PostAtsApplicationsApplicationIdAttachmentsRequestBodyGreenhouse), workable: T.nilable(Models::Components::PostAtsApplicationsApplicationIdAttachmentsRequestBodyWorkable)).void }
        def initialize(oracle: nil, greenhouse: nil, workable: nil)
          @oracle = oracle
          @greenhouse = greenhouse
          @workable = workable
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @oracle == other.oracle
          return false unless @greenhouse == other.greenhouse
          return false unless @workable == other.workable
          true
        end
      end
    end
  end
end
