# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Components
      # Fields specific to Avature.
      class PostAtsCandidatesRequestBodyAvature
        extend T::Sig
        include Crystalline::MetadataFields


        field :workflow, Crystalline::Nilable.new(Models::Components::PostAtsCandidatesRequestBodyWorkflow), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('workflow') } }

        sig { params(workflow: T.nilable(Models::Components::PostAtsCandidatesRequestBodyWorkflow)).void }
        def initialize(workflow: nil)
          @workflow = workflow
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @workflow == other.workflow
          true
        end
      end
    end
  end
end
