# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Components

      class PostAtsJobsJobIdApplicationsRequestBodyLanguageDatumLanguageReference
        extend T::Sig
        include Crystalline::MetadataFields


        field :wid, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('WID') } }

        sig { params(wid: T.nilable(::String)).void }
        def initialize(wid: nil)
          @wid = wid
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @wid == other.wid
          true
        end
      end
    end
  end
end
