# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Components

      class PostAtsImportTrackedApplicationRequestBodyOnlyfyApplicationID
        extend T::Sig
        include Crystalline::MetadataFields

        # Uses the `/v1/application/{id}` endpoint to retrieve the application.
        field :id_type, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('id_type'), required: true } }

        field :application_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('application_id'), required: true } }

        sig { params(id_type: ::String, application_id: ::String).void }
        def initialize(id_type:, application_id:)
          unless id_type == 'application_id'
            raise ArgumentError, 'Invalid value for id_type'
          end
          @id_type = 'application_id'
          @application_id = application_id
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @id_type == other.id_type
          return false unless @application_id == other.application_id
          true
        end
      end
    end
  end
end
