# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Components
      # Fields specific to GuideCom.
      class PostAtsJobsJobIdApplicationsRequestBodyHrworks
        extend T::Sig
        include Crystalline::MetadataFields

        # Fields that we will pass through to HRWorks's `Job Application` object. This API is used: https://developers.hrworks.de/docs/hrworks-api-v2/53021f035f62d-post-job-applications
        field :job_application, Crystalline::Nilable.new(Crystalline::Hash.new(Symbol, ::Object)), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('jobApplication') } }

        sig { params(job_application: T.nilable(T::Hash[Symbol, ::Object])).void }
        def initialize(job_application: nil)
          @job_application = job_application
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @job_application == other.job_application
          true
        end
      end
    end
  end
end
