# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Components
      # Fields specific to Bullhorn.
      class PostAtsJobsJobIdApplicationsRequestBodyBullhorn
        extend T::Sig
        include Crystalline::MetadataFields

        # Fields that we will pass through to Bullhorn's `Candidate` object.
        field :candidate, Crystalline::Nilable.new(Crystalline::Hash.new(Symbol, ::Object)), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('candidate') } }
        # Fields that we will pass through to Bullhorn's `JobSubmission` object.
        field :job_submission, Crystalline::Nilable.new(Crystalline::Hash.new(Symbol, ::Object)), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('job_submission') } }

        sig { params(candidate: T.nilable(T::Hash[Symbol, ::Object]), job_submission: T.nilable(T::Hash[Symbol, ::Object])).void }
        def initialize(candidate: nil, job_submission: nil)
          @candidate = candidate
          @job_submission = job_submission
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @candidate == other.candidate
          return false unless @job_submission == other.job_submission
          true
        end
      end
    end
  end
end
