# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Components

      class PostAtsImportTrackedApplicationPositiveResponseData
        extend T::Sig
        include Crystalline::MetadataFields


        field :id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('id'), required: true } }

        field :imported_id, Models::Components::ImportedId, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('imported_id'), required: true } }
        # YYYY-MM-DDTHH:mm:ss.sssZ
        # https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString
        field :tracked_at, Crystalline::Nilable.new(::DateTime), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('tracked_at'), required: true, 'decoder': Utils.datetime_from_iso_format(false) } }

        sig { params(id: ::String, imported_id: Models::Components::ImportedId, tracked_at: T.nilable(::DateTime)).void }
        def initialize(id:, imported_id:, tracked_at: nil)
          @id = id
          @imported_id = imported_id
          @tracked_at = tracked_at
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @id == other.id
          return false unless @imported_id == other.imported_id
          return false unless @tracked_at == other.tracked_at
          true
        end
      end
    end
  end
end
