# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Components
      # PostAtsCandidatesRequestBodyAttachmentType - Type of the attachment in the ATS. This may affect where the uploaded file will be shown in your customer's system.
      class PostAtsCandidatesRequestBodyAttachmentType < T::Enum


        enums do
          CV = new('CV')
          COVER_LETTER = new('COVER_LETTER')
          OTHER = new('OTHER')
        end
      end
    end
  end
end
