# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Components

      class PostAtsApplicationsApplicationIdAttachmentsRequestBody
        extend T::Sig
        include Crystalline::MetadataFields


        field :attachment, Models::Components::PostAtsApplicationsApplicationIdAttachmentsRequestBodyAttachment, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('attachment'), required: true } }

        field :remote_fields, Crystalline::Nilable.new(Models::Components::PostAtsApplicationsApplicationIdAttachmentsRequestBodyRemoteFields), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('remote_fields') } }

        sig { params(attachment: Models::Components::PostAtsApplicationsApplicationIdAttachmentsRequestBodyAttachment, remote_fields: T.nilable(Models::Components::PostAtsApplicationsApplicationIdAttachmentsRequestBodyRemoteFields)).void }
        def initialize(attachment:, remote_fields: nil)
          @attachment = attachment
          @remote_fields = remote_fields
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @attachment == other.attachment
          return false unless @remote_fields == other.remote_fields
          true
        end
      end
    end
  end
end
