# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Components
      # PostForceSyncRequestBodyType - The type of the triggered sync.
      class PostForceSyncRequestBodyType < T::Enum


        enums do
          FULL = new('FULL')
          DELTA = new('DELTA')
        end
      end
    end
  end
end
