# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Components

      class PostAtsCandidatesRequestBodyJobApplicationData
        extend T::Sig
        include Crystalline::MetadataFields


        field :job_applied_to_data, Crystalline::Nilable.new(Models::Components::PostAtsCandidatesRequestBodyJobAppliedToData), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('Job_Applied_To_Data') } }

        field :resume_data, Crystalline::Nilable.new(Models::Components::PostAtsCandidatesRequestBodyResumeData), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('Resume_Data') } }

        sig { params(job_applied_to_data: T.nilable(Models::Components::PostAtsCandidatesRequestBodyJobAppliedToData), resume_data: T.nilable(Models::Components::PostAtsCandidatesRequestBodyResumeData)).void }
        def initialize(job_applied_to_data: nil, resume_data: nil)
          @job_applied_to_data = job_applied_to_data
          @resume_data = resume_data
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @job_applied_to_data == other.job_applied_to_data
          return false unless @resume_data == other.resume_data
          true
        end
      end
    end
  end
end
