# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Components

      class PostAtsCandidatesRequestBodyCandidateData
        extend T::Sig
        include Crystalline::MetadataFields


        field :name_detail_data, Crystalline::Nilable.new(Models::Components::PostAtsCandidatesRequestBodyNameDetailData), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('Name_Detail_Data') } }
        # Used to set the candidate's primary language
        field :language_reference, Crystalline::Nilable.new(Models::Components::PostAtsCandidatesRequestBodyLanguageReference), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('Language_Reference') } }

        field :job_application_data, Crystalline::Nilable.new(Models::Components::PostAtsCandidatesRequestBodyJobApplicationData), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('Job_Application_Data') } }

        field :contact_data, Crystalline::Nilable.new(Models::Components::PostAtsCandidatesRequestBodyContactData), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('Contact_Data') } }
        # Reference to the Worker (employee) to link the candidate to. Provide either WID or Employee_ID.
        field :worker_reference, Crystalline::Nilable.new(Models::Components::PostAtsCandidatesRequestBodyWorkerReference), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('Worker_Reference') } }

        sig { params(name_detail_data: T.nilable(Models::Components::PostAtsCandidatesRequestBodyNameDetailData), language_reference: T.nilable(Models::Components::PostAtsCandidatesRequestBodyLanguageReference), job_application_data: T.nilable(Models::Components::PostAtsCandidatesRequestBodyJobApplicationData), contact_data: T.nilable(Models::Components::PostAtsCandidatesRequestBodyContactData), worker_reference: T.nilable(Models::Components::PostAtsCandidatesRequestBodyWorkerReference)).void }
        def initialize(name_detail_data: nil, language_reference: nil, job_application_data: nil, contact_data: nil, worker_reference: nil)
          @name_detail_data = name_detail_data
          @language_reference = language_reference
          @job_application_data = job_application_data
          @contact_data = contact_data
          @worker_reference = worker_reference
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @name_detail_data == other.name_detail_data
          return false unless @language_reference == other.language_reference
          return false unless @job_application_data == other.job_application_data
          return false unless @contact_data == other.contact_data
          return false unless @worker_reference == other.worker_reference
          true
        end
      end
    end
  end
end
