# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Components
      # Additional fields that we will pass through to specific HRIS systems.
      class PostHrisAbsencesRequestBodyRemoteFields
        extend T::Sig
        include Crystalline::MetadataFields

        # Fields specific to ADP Workforce Now.
        field :adpworkforcenow, Crystalline::Nilable.new(Models::Components::PostHrisAbsencesRequestBodyAdpworkforcenow), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('adpworkforcenow') } }

        sig { params(adpworkforcenow: T.nilable(Models::Components::PostHrisAbsencesRequestBodyAdpworkforcenow)).void }
        def initialize(adpworkforcenow: nil)
          @adpworkforcenow = adpworkforcenow
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @adpworkforcenow == other.adpworkforcenow
          true
        end
      end
    end
  end
end
