# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Components

      class PostAtsCandidatesRequestBodyAdditionalPhoneNumber
        extend T::Sig
        include Crystalline::MetadataFields


        field :type, Models::Components::PostAtsCandidatesRequestBodyAdditionalPhoneNumberType, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('type'), required: true, 'decoder': Utils.enum_from_string(Models::Components::PostAtsCandidatesRequestBodyAdditionalPhoneNumberType, false) } }

        field :phone_number, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('phone_number'), required: true } }

        sig { params(type: Models::Components::PostAtsCandidatesRequestBodyAdditionalPhoneNumberType, phone_number: ::String).void }
        def initialize(type:, phone_number:)
          @type = type
          @phone_number = phone_number
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @type == other.type
          return false unless @phone_number == other.phone_number
          true
        end
      end
    end
  end
end
