# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Components

      class PostAtsCandidatesRequestBodyLanguageDatum
        extend T::Sig
        include Crystalline::MetadataFields


        field :language_reference, Crystalline::Nilable.new(Models::Components::PostAtsCandidatesRequestBodyLanguageDatumLanguageReference), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('Language_Reference') } }

        field :language, Crystalline::Nilable.new(Models::Components::PostAtsCandidatesRequestBodyLanguage), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('Language') } }

        sig { params(language_reference: T.nilable(Models::Components::PostAtsCandidatesRequestBodyLanguageDatumLanguageReference), language: T.nilable(Models::Components::PostAtsCandidatesRequestBodyLanguage)).void }
        def initialize(language_reference: nil, language: nil)
          @language_reference = language_reference
          @language = language
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @language_reference == other.language_reference
          return false unless @language == other.language
          true
        end
      end
    end
  end
end
