# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Components

      class PostAtsCandidatesRequestBodyResumeData
        extend T::Sig
        include Crystalline::MetadataFields


        field :education_data, Crystalline::Nilable.new(Crystalline::Array.new(Models::Components::PostAtsCandidatesRequestBodyEducationDatum)), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('Education_Data') } }

        field :skill_data, Crystalline::Nilable.new(Crystalline::Array.new(Models::Components::PostAtsCandidatesRequestBodySkillDatum)), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('Skill_Data') } }

        field :language_data, Crystalline::Nilable.new(Crystalline::Array.new(Models::Components::PostAtsCandidatesRequestBodyLanguageDatum)), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('Language_Data') } }

        field :experience_data, Crystalline::Nilable.new(Crystalline::Array.new(Models::Components::PostAtsCandidatesRequestBodyExperienceDatum)), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('Experience_Data') } }

        sig { params(education_data: T.nilable(T::Array[Models::Components::PostAtsCandidatesRequestBodyEducationDatum]), skill_data: T.nilable(T::Array[Models::Components::PostAtsCandidatesRequestBodySkillDatum]), language_data: T.nilable(T::Array[Models::Components::PostAtsCandidatesRequestBodyLanguageDatum]), experience_data: T.nilable(T::Array[Models::Components::PostAtsCandidatesRequestBodyExperienceDatum])).void }
        def initialize(education_data: nil, skill_data: nil, language_data: nil, experience_data: nil)
          @education_data = education_data
          @skill_data = skill_data
          @language_data = language_data
          @experience_data = experience_data
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @education_data == other.education_data
          return false unless @skill_data == other.skill_data
          return false unless @language_data == other.language_data
          return false unless @experience_data == other.experience_data
          true
        end
      end
    end
  end
end
