# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Components

      class PostAtsJobsJobIdApplicationsPositiveResponseAnswer3
        extend T::Sig
        include Crystalline::MetadataFields


        field :choices, Crystalline::Nilable.new(Crystalline::Array.new(::String)), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('choices') } }

        sig { params(choices: T.nilable(T::Array[::String])).void }
        def initialize(choices: nil)
          @choices = choices
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @choices == other.choices
          true
        end
      end
    end
  end
end
