# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Components

      class PostAtsCandidatesPositiveResponseEmailAddress
        extend T::Sig
        include Crystalline::MetadataFields

        # Kombo exposes type information through this field. If we don't get any information from the tool, we will set this to `null`.
        field :type, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('type'), required: true } }

        field :email_address, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('email_address') } }

        sig { params(type: T.nilable(::String), email_address: T.nilable(::String)).void }
        def initialize(type: nil, email_address: nil)
          @type = type
          @email_address = email_address
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @type == other.type
          return false unless @email_address == other.email_address
          true
        end
      end
    end
  end
end
