# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Components
      # Additional candidate fields for P&I Loga that will be mapped to the application form.
      class PostAtsCandidatesRequestBodyPilogaCandidate
        extend T::Sig
        include Crystalline::MetadataFields

        # The street address of the candidate.
        field :street, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('street') } }

        sig { params(street: T.nilable(::String)).void }
        def initialize(street: nil)
          @street = street
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @street == other.street
          true
        end
      end
    end
  end
end
