# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Components

      class PostAtsCandidatesRequestBodySkillDatum
        extend T::Sig
        include Crystalline::MetadataFields


        field :skill_name, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('Skill_Name') } }

        sig { params(skill_name: T.nilable(::String)).void }
        def initialize(skill_name: nil)
          @skill_name = skill_name
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @skill_name == other.skill_name
          true
        end
      end
    end
  end
end
