# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Components

      class PostAtsJobsJobIdApplicationsPositiveResponseScreeningQuestionAnswer4
        extend T::Sig
        include Crystalline::MetadataFields


        field :answer, Models::Components::PostAtsJobsJobIdApplicationsPositiveResponseAnswer4, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('answer'), required: true } }

        field :question, Models::Components::PostAtsJobsJobIdApplicationsPositiveResponseQuestionBoolean, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('question'), required: true } }

        sig { params(answer: Models::Components::PostAtsJobsJobIdApplicationsPositiveResponseAnswer4, question: Models::Components::PostAtsJobsJobIdApplicationsPositiveResponseQuestionBoolean).void }
        def initialize(answer:, question:)
          @answer = answer
          @question = question
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @answer == other.answer
          return false unless @question == other.question
          true
        end
      end
    end
  end
end
