# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Components

      class SalaryPeriod < T::Enum


        enums do
          YEAR = new('YEAR')
          MONTH = new('MONTH')
          TWO_WEEKS = new('TWO_WEEKS')
          WEEK = new('WEEK')
          DAY = new('DAY')
          HOUR = new('HOUR')
        end
      end
    end
  end
end
