# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Components

      class Schema2Array1
        extend T::Sig
        include Crystalline::MetadataFields


        field :label, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('label'), required: true } }

        field :required, Crystalline::Boolean.new, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('required'), required: true } }

        field :type, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('type'), required: true } }

        field :item_type, Crystalline::Union.new(Models::Components::Schema2Text, Models::Components::Schema2Number, Models::Components::Schema2Date, Models::Components::Schema2SingleSelect, Models::Components::Schema2MultiSelect, Models::Components::Schema2Checkbox, Models::Components::Schema2Object1, Models::Components::Schema2Array1, Models::Components::Schema2File), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('item_type'), required: true }, 'discriminator': 'type', 'discriminator_mapping': { 'text' => Models::Components::Schema2Text, 'number' => Models::Components::Schema2Number, 'date' => Models::Components::Schema2Date, 'single_select' => Models::Components::Schema2SingleSelect, 'multi_select' => Models::Components::Schema2MultiSelect, 'checkbox' => Models::Components::Schema2Checkbox, 'object' => Models::Components::Schema2Object1, 'array' => Models::Components::Schema2Array1, 'file' => Models::Components::Schema2File } }

        field :description, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('description') } }

        field :unified_key, Crystalline::Nilable.new(Models::Components::Schema2UnifiedKey7), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('unified_key'), 'decoder': Utils.enum_from_string(Models::Components::Schema2UnifiedKey7, true) } }

        field :min_items, Crystalline::Nilable.new(::Float), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('min_items') } }

        field :max_items, Crystalline::Nilable.new(::Float), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('max_items') } }

        sig { params(label: ::String, required: T::Boolean, type: ::String, item_type: T.any(Models::Components::Schema2Text, Models::Components::Schema2Number, Models::Components::Schema2Date, Models::Components::Schema2SingleSelect, Models::Components::Schema2MultiSelect, Models::Components::Schema2Checkbox, Models::Components::Schema2Object1, Models::Components::Schema2Array1, Models::Components::Schema2File), description: T.nilable(::String), unified_key: T.nilable(Models::Components::Schema2UnifiedKey7), min_items: T.nilable(::Float), max_items: T.nilable(::Float)).void }
        def initialize(label:, required:, type:, item_type:, description: nil, unified_key: nil, min_items: nil, max_items: nil)
          @label = label
          @required = required
          unless type == 'array'
            raise ArgumentError, 'Invalid value for type'
          end
          @type = 'array'
          @item_type = item_type
          @description = description
          @unified_key = unified_key
          @min_items = min_items
          @max_items = max_items
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @label == other.label
          return false unless @required == other.required
          return false unless @type == other.type
          return false unless @item_type == other.item_type
          return false unless @description == other.description
          return false unless @unified_key == other.unified_key
          return false unless @min_items == other.min_items
          return false unless @max_items == other.max_items
          true
        end
      end
    end
  end
end
