# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Components
      # SyncFinishedWebhookPayloadType - Type of the webhook event
      class SyncFinishedWebhookPayloadType < T::Enum


        enums do
          SYNC_FINISHED = new('sync-finished')
        end
      end
    end
  end
end
