# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Components

      class SyncFinishedWebhookPayload
        extend T::Sig
        include Crystalline::MetadataFields

        # Unique identifier for this webhook event
        field :id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('id'), required: true } }
        # Type of the webhook event
        field :type, Models::Components::SyncFinishedWebhookPayloadType, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('type'), required: true, 'decoder': Utils.enum_from_string(Models::Components::SyncFinishedWebhookPayloadType, false) } }

        field :data, Models::Components::SyncFinishedWebhookPayloadData, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('data'), required: true } }

        sig { params(id: ::String, type: Models::Components::SyncFinishedWebhookPayloadType, data: Models::Components::SyncFinishedWebhookPayloadData).void }
        def initialize(id:, type:, data:)
          @id = id
          @type = type
          @data = data
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @id == other.id
          return false unless @type == other.type
          return false unless @data == other.data
          true
        end
      end
    end
  end
end
