# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Components

      class SyncFinishedWebhookPayloadData
        extend T::Sig
        include Crystalline::MetadataFields

        # The unique identifier of the sync operation.
        field :sync_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('sync_id'), required: true } }
        # The final state of the sync operation (e.g., `SUCCEEDED`, `FAILED`).
        field :sync_state, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('sync_state'), required: true } }
        # ISO 8601 timestamp when the sync operation started.
        field :sync_started_at, ::DateTime, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('sync_started_at'), required: true, 'decoder': Utils.datetime_from_iso_format(false) } }
        # ISO 8601 timestamp when the sync operation completed.
        field :sync_ended_at, ::DateTime, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('sync_ended_at'), required: true, 'decoder': Utils.datetime_from_iso_format(false) } }
        # Duration of the sync operation in seconds.
        field :sync_duration_seconds, ::Integer, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('sync_duration_seconds'), required: true } }
        # The unique identifier of the integration.
        field :integration_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('integration_id'), required: true } }
        # The name of the integrated tool (e.g., "personio", "greenhouse").
        field :integration_tool, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('integration_tool'), required: true } }
        # The category of the integration (HRIS, ATS, ASSESSMENT, or LMS).
        field :integration_category, Models::Components::SyncFinishedWebhookPayloadIntegrationCategory, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('integration_category'), required: true, 'decoder': Utils.enum_from_string(Models::Components::SyncFinishedWebhookPayloadIntegrationCategory, false) } }
        # Information about the end user who created the integration.
        field :end_user, Models::Components::SyncFinishedWebhookPayloadEndUser, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('end_user'), required: true } }
        # URL to view detailed logs for the operation.
        field :log_url, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('log_url'), required: true } }

        sig { params(sync_id: ::String, sync_state: ::String, sync_started_at: ::DateTime, sync_ended_at: ::DateTime, sync_duration_seconds: ::Integer, integration_id: ::String, integration_tool: ::String, integration_category: Models::Components::SyncFinishedWebhookPayloadIntegrationCategory, end_user: Models::Components::SyncFinishedWebhookPayloadEndUser, log_url: ::String).void }
        def initialize(sync_id:, sync_state:, sync_started_at:, sync_ended_at:, sync_duration_seconds:, integration_id:, integration_tool:, integration_category:, end_user:, log_url:)
          @sync_id = sync_id
          @sync_state = sync_state
          @sync_started_at = sync_started_at
          @sync_ended_at = sync_ended_at
          @sync_duration_seconds = sync_duration_seconds
          @integration_id = integration_id
          @integration_tool = integration_tool
          @integration_category = integration_category
          @end_user = end_user
          @log_url = log_url
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @sync_id == other.sync_id
          return false unless @sync_state == other.sync_state
          return false unless @sync_started_at == other.sync_started_at
          return false unless @sync_ended_at == other.sync_ended_at
          return false unless @sync_duration_seconds == other.sync_duration_seconds
          return false unless @integration_id == other.integration_id
          return false unless @integration_tool == other.integration_tool
          return false unless @integration_category == other.integration_category
          return false unless @end_user == other.end_user
          return false unless @log_url == other.log_url
          true
        end
      end
    end
  end
end
