# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Components

      class User
        extend T::Sig
        include Crystalline::MetadataFields

        # The globally unique ID of this object generated by Kombo. We recommend using this as a stable primary key for syncing.
        field :id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('id'), required: true } }
        # The raw ID of the object in the remote system. We don't recommend using this as a primary key on your side as it might sometimes be compromised of multiple identifiers if a system doesn't provide a clear primary key.
        field :remote_id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('remote_id'), required: true } }
        # First name of the user.
        field :first_name, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('first_name'), required: true } }
        # Last name of the user.
        field :last_name, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('last_name'), required: true } }
        # Email of the user. If the email address is invalid, it will be set to null.
        field :email, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('email') } }

        sig { params(id: ::String, remote_id: T.nilable(::String), first_name: T.nilable(::String), last_name: T.nilable(::String), email: T.nilable(::String)).void }
        def initialize(id:, remote_id: nil, first_name: nil, last_name: nil, email: nil)
          @id = id
          @remote_id = remote_id
          @first_name = first_name
          @last_name = last_name
          @email = email
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @id == other.id
          return false unless @remote_id == other.remote_id
          return false unless @first_name == other.first_name
          return false unless @last_name == other.last_name
          return false unless @email == other.email
          true
        end
      end
    end
  end
end
