# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations

      class DeleteHrisAbsencesAbsenceIdRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # The Kombo ID of the absence
        field :absence_id, ::String, { 'path_param': { 'field_name': 'absence_id', 'style': 'simple', 'explode': false } }
        # DELETE /hris/absences/:absence_id Request body
        field :body, Models::Components::DeleteHrisAbsencesAbsenceIdRequestBody, { 'request': { 'media_type': 'application/json' } }
        # ID of the integration you want to interact with.
        field :integration_id, Crystalline::Nilable.new(::String), { 'header': { 'field_name': 'X-Integration-Id', 'style': 'simple', 'explode': false } }

        sig { params(absence_id: ::String, body: Models::Components::DeleteHrisAbsencesAbsenceIdRequestBody, integration_id: T.nilable(::String)).void }
        def initialize(absence_id:, body:, integration_id: nil)
          @absence_id = absence_id
          @body = body
          @integration_id = integration_id
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @absence_id == other.absence_id
          return false unless @body == other.body
          return false unless @integration_id == other.integration_id
          true
        end
      end
    end
  end
end
