# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations

      class GetAtsCandidatesCandidateIdAttachmentsRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # The Kombo ID of the candidate you want to obtain attachments for.
        field :candidate_id, ::String, { 'path_param': { 'field_name': 'candidate_id', 'style': 'simple', 'explode': false } }
        # ID of the integration you want to interact with.
        field :integration_id, Crystalline::Nilable.new(::String), { 'header': { 'field_name': 'X-Integration-Id', 'style': 'simple', 'explode': false } }

        sig { params(candidate_id: ::String, integration_id: T.nilable(::String)).void }
        def initialize(candidate_id:, integration_id: nil)
          @candidate_id = candidate_id
          @integration_id = integration_id
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @candidate_id == other.candidate_id
          return false unless @integration_id == other.integration_id
          true
        end
      end
    end
  end
end
