# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Kombo
  module Models
    module Operations

      class GetConnectIntegrationByTokenTokenRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # GET /connect/integration-by-token/:token Parameter
        field :token, ::String, { 'path_param': { 'field_name': 'token', 'style': 'simple', 'explode': false } }

        sig { params(token: ::String).void }
        def initialize(token:)
          @token = token
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @token == other.token
          true
        end
      end
    end
  end
end
