# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations

      class GetCheckApiKeyResponse
        extend T::Sig
        include Crystalline::MetadataFields

        # HTTP response content type for this operation
        field :content_type, ::String
        # HTTP response status code for this operation
        field :status_code, ::Integer
        # Raw HTTP response; suitable for custom response parsing
        field :raw_response, ::Faraday::Response
        # GET /check-api-key Positive response
        field :get_check_api_key_positive_response, Crystalline::Nilable.new(Models::Shared::GetCheckApiKeyPositiveResponse)

        sig { params(content_type: ::String, status_code: ::Integer, raw_response: ::Faraday::Response, get_check_api_key_positive_response: T.nilable(Models::Shared::GetCheckApiKeyPositiveResponse)).void }
        def initialize(content_type:, status_code:, raw_response:, get_check_api_key_positive_response: nil)
          @content_type = content_type
          @status_code = status_code
          @raw_response = raw_response
          @get_check_api_key_positive_response = get_check_api_key_positive_response
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @content_type == other.content_type
          return false unless @status_code == other.status_code
          return false unless @raw_response == other.raw_response
          return false unless @get_check_api_key_positive_response == other.get_check_api_key_positive_response
          true
        end
      end
    end
  end
end
