# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations

      class PostForceSyncRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # POST /force-sync Request body
        field :body, Models::Components::PostForceSyncRequestBody, { 'request': { 'media_type': 'application/json' } }
        # ID of the integration you want to interact with.
        field :integration_id, Crystalline::Nilable.new(::String), { 'header': { 'field_name': 'X-Integration-Id', 'style': 'simple', 'explode': false } }

        sig { params(body: Models::Components::PostForceSyncRequestBody, integration_id: T.nilable(::String)).void }
        def initialize(body:, integration_id: nil)
          @body = body
          @integration_id = integration_id
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @body == other.body
          return false unless @integration_id == other.integration_id
          true
        end
      end
    end
  end
end
