# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations

      class PostHrisEmployeesEmployeeIdDocumentsRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # POST /hris/employees/:employee_id/documents Parameter
        field :employee_id, ::String, { 'path_param': { 'field_name': 'employee_id', 'style': 'simple', 'explode': false } }
        # POST /hris/employees/:employee_id/documents Request body
        field :body, Models::Components::PostHrisEmployeesEmployeeIdDocumentsRequestBody, { 'request': { 'media_type': 'application/json' } }
        # ID of the integration you want to interact with.
        field :integration_id, Crystalline::Nilable.new(::String), { 'header': { 'field_name': 'X-Integration-Id', 'style': 'simple', 'explode': false } }

        sig { params(employee_id: ::String, body: Models::Components::PostHrisEmployeesEmployeeIdDocumentsRequestBody, integration_id: T.nilable(::String)).void }
        def initialize(employee_id:, body:, integration_id: nil)
          @employee_id = employee_id
          @body = body
          @integration_id = integration_id
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @employee_id == other.employee_id
          return false unless @body == other.body
          return false unless @integration_id == other.integration_id
          true
        end
      end
    end
  end
end
