# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations

      class PutAssessmentOrdersAssessmentOrderIdResultRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # PUT /assessment/orders/:assessment_order_id/result Parameter
        field :assessment_order_id, ::String, { 'path_param': { 'field_name': 'assessment_order_id', 'style': 'simple', 'explode': false } }
        # PUT /assessment/orders/:assessment_order_id/result Request body
        field :body, Models::Components::PutAssessmentOrdersAssessmentOrderIdResultRequestBody, { 'request': { 'media_type': 'application/json' } }
        # ID of the integration you want to interact with.
        field :integration_id, Crystalline::Nilable.new(::String), { 'header': { 'field_name': 'X-Integration-Id', 'style': 'simple', 'explode': false } }

        sig { params(assessment_order_id: ::String, body: Models::Components::PutAssessmentOrdersAssessmentOrderIdResultRequestBody, integration_id: T.nilable(::String)).void }
        def initialize(assessment_order_id:, body:, integration_id: nil)
          @assessment_order_id = assessment_order_id
          @body = body
          @integration_id = integration_id
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @assessment_order_id == other.assessment_order_id
          return false unless @body == other.body
          return false unless @integration_id == other.integration_id
          true
        end
      end
    end
  end
end
