# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations

      class PutIntegrationsIntegrationIdEnabledRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # PUT /integrations/:integration_id/enabled Parameter
        field :integration_id, ::String, { 'path_param': { 'field_name': 'integration_id', 'style': 'simple', 'explode': false } }
        # PUT /integrations/:integration_id/enabled Request body
        field :body, Models::Shared::PutIntegrationsIntegrationIdEnabledRequestBody, { 'request': { 'media_type': 'application/json' } }

        sig { params(integration_id: ::String, body: Models::Shared::PutIntegrationsIntegrationIdEnabledRequestBody).void }
        def initialize(integration_id:, body:)
          @integration_id = integration_id
          @body = body
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @integration_id == other.integration_id
          return false unless @body == other.body
          true
        end
      end
    end
  end
end
