# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations

      class PutIntegrationsIntegrationIdCustomFieldsCustomFieldIdRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # The unique ID of the integration where the custom field mapping should be updated
        field :integration_id, ::String, { 'path_param': { 'field_name': 'integration_id', 'style': 'simple', 'explode': false } }
        # The unique ID of the custom field that should be updated
        field :custom_field_id, ::String, { 'path_param': { 'field_name': 'custom_field_id', 'style': 'simple', 'explode': false } }
        # PUT /integrations/:integration_id/custom-fields/:custom_field_id Request body
        field :body, Models::Components::PutIntegrationsIntegrationIdCustomFieldsCustomFieldIdRequestBody, { 'request': { 'media_type': 'application/json' } }

        sig { params(integration_id: ::String, custom_field_id: ::String, body: Models::Components::PutIntegrationsIntegrationIdCustomFieldsCustomFieldIdRequestBody).void }
        def initialize(integration_id:, custom_field_id:, body:)
          @integration_id = integration_id
          @custom_field_id = custom_field_id
          @body = body
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @integration_id == other.integration_id
          return false unless @custom_field_id == other.custom_field_id
          return false unless @body == other.body
          true
        end
      end
    end
  end
end
