# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Errors
      # The standard error response with the error codes for the HRIS use case.
      class KomboHrisError < StandardError
        extend T::Sig
        include Crystalline::MetadataFields


        field :status, Models::Components::KomboHrisErrorStatus, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('status'), required: true, 'decoder': Utils.enum_from_string(Models::Components::KomboHrisErrorStatus, false) } }
        # Error details with structured code for programmatic handling.
        field :error, Models::Components::KomboHrisErrorError, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('error'), required: true } }
        # Raw HTTP response; suitable for custom response parsing
        field :raw_response, Crystalline::Nilable.new(::Faraday::Response), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('-') } }

        sig { params(status: Models::Components::KomboHrisErrorStatus, error: Models::Components::KomboHrisErrorError, raw_response: T.nilable(::Faraday::Response)).void }
        def initialize(status:, error:, raw_response: nil)
          @status = status
          @error = error
          @raw_response = raw_response
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @status == other.status
          return false unless @error == other.error
          return false unless @raw_response == other.raw_response
          true
        end
      end
    end
  end
end
